### ISSUE TITLE
Отключить вывод "Информация - " для обычных логов

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#10]
ИМХО было бы удобно отключить вывод "Информация - " для логов уровня "информация".
сейчас в логах большое количество строк "Информация" является ненужным "шумом" :(

ИМХО я где-то в log4ХХХ видел подобную фичу.

**Comment by EvilBeaver** [comment]
Уже появилось. Не совсем как в log4j, но возможность изменить формат уже есть

-----Исходное сообщение-----
От: "Artur Ayukhanov" notifications@github.com
Отправлено: ‎21.‎09.‎2015 17:49
Кому: "EvilBeaver/oscript-library" oscript-library@noreply.github.com
Тема: [oscript-library] Отключить вывод "Информация - " для обычных логов (#10)

ИМХО было бы удобно отключить вывод "Информация - " для логов уровня "информация".
сейчас в логах большое количество строк "Информация" является ненужным "шумом" :(
ИМХО я где-то в log4ХХХ видел подобную фичу.
