### ISSUE TITLE
[cmdline] Параметры-синонимы

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/oscript-library#100]
Хочется чтобы была возможность при добавлении описаний параметров указывать их синонимы. Например полное --version и краткое -v. При этом разработчику скрипта при анализе флагов/переданных параметров достаточно проверить наличие полной версии параметра, даже есть пользователь передал краткое.

**Comment by artbear** [comment]
+1 
Давно об этом задумывался.

**Comment by EvilBeaver** [comment]
Предлагаю делать в рамках #66

**Comment by nixel2007** [comment]
@EvilBeaver не совсем понимаю, как связаны эти две задачи.

**Comment by EvilBeaver** [comment]
Расширять API cmdline удобнее в стиле fluent

**Comment by nixel2007** [comment]
Реализовано в библиотеке cli. В связи с остановкой развития cmdline, предлагаю закрыть.
