### ISSUE TITLE
Добавить описание к процедурам прогонки тестов и testrunner.os

### ISSUE THREAD

**Issue by JohnyDeath** [EvilBeaver/oscript-library#102]

**Comment by artbear** [comment]
Женя, точнее сформулируй свои ожидания. Пока что непонятно.

**Comment by JohnyDeath** [comment]
Ожидал увидеть здесь https://github.com/EvilBeaver/oscript-library/tree/develop/tests
вот это: http://oscript.io/docs/page/testing
