### ISSUE TITLE
[gitsync] Документировать форматы файлов версий и авторов

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#104]

**Comment by artbear** [comment]
Выполнено.

**Comment by EvilBeaver** [comment]
А где выполнено?

**Comment by artbear** [comment]
https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/readme.md#Файлы-настройки

**Comment by artbear** [comment]
@EvilBeaver Я довольно сильно дополнил доку сегодня
Что скажешь?

**Comment by artbear** [comment]
Все это в рамках работы по #82 и развертыванию гитсинк на новых машинах

**Comment by EvilBeaver** [comment]
Классно, спасибо!
Еще бы поведение gitsync сделать таким, как в #82

**Comment by artbear** [comment]
@EvilBeaver Я как раз вчера и начал обсуждение для изменения логики работы.
Сегодня продолжаем в гиттере
