### ISSUE TITLE
[opm] Работа через прокси

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#105]
На данный момент opm с прокси не работает.
Хорошо бы добавить.

**Comment by asosnoviy** [comment]
Столкнулся с проблемой при реализации.  
Как мне кажется В 1се  указание пользовательских настроек происходит методом  Установить.

```
HTTPproxy =  Новый ИнтернетПрокси(Ложь); 
HTTPproxy.Установить("HTTP",СерверПрокси,ПортПрокси,ПользовательПрокси,ПарольПрокси,Истина);
```

В Oscript у ИнтернетПрокси нет метода Установить().
Посмотрел исходники [InternetProxyContex](https://github.com/EvilBeaver/OneScript/blob/develop/src/ScriptEngine.HostedScript/Library/Http/InternetProxyContext.cs) и не увидел (может плохо смотрел) там возможности установки адреса прокси сервера.   

```
$ oscript -encoding=utf-8 opm.os help config
config - Задать пользовательские настройки
Параметры:
 <-proxyusedefault> - Использовать ПроксиПоУмолчанию (системные настройки)
 -proxyserver - Адресс прокси
 -proxyport - Порт прокси
 -proxyuser - Пользователь прокси
 -proxypass - Пароль прокси
```

По этому из всех настроек реализовать удалось только верхнюю.

**Comment by EvilBeaver** [comment]
Да, это повод завести задачу на односкрипт. Я это не реализовал, т.к. у меня нет сетевой среды, в которой это можно было бы погонять. А воссоздавать виртуально было лениво.

@int-it сделай, пожалуйста, как будто оно работает. Я допилю движок и код opm менять не придется.

**Comment by asosnoviy** [comment]
Хорошо, тогда сейчас -proxyusedefault будет работать, а если установить кастомные настройки то будет падать opm install с ошибкой несуществующего метода Установить().

**Comment by EvilBeaver** [comment]
да, пусть. В большинстве случаев, системного прокси достаточно.

**Comment by EvilBeaver** [comment]
Закрываю. Пофикшено в новом репо opm
