### ISSUE TITLE
[logos] Добавить аналог СтрШаблон в функции вывода лога

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#107]
Для сложных выражений сейчас часто приходится писать функции вывода совместно с `СтрШаблон`
Например:

```
Лог.Отладка(СтрШаблон("Выполняю узел <%1>, тело <%2>", Узел.ТипШага, Узел.Тело));
```

Намного удобнее и проще сразу писать следующий код без `СтрШаблон`:

```
Лог.Отладка("Выполняю узел <%1>, тело <%2>", Узел.ТипШага, Узел.Тело);
```

Также можно гарантировать обратную совместимость

ИМХО реализация несложна - куча параметров с пустыми значениями по умолчанию и получение итоговой строки из `СтрШаблон`

**Comment by EvilBeaver** [comment]
Pull request?

**Comment by artbear** [comment]
Если нет возражений по существу, конечно, я сделаю.

**Comment by artbear** [comment]
Товарищи, если возражений нет, реализую?
жду ответов пару дней.

**Comment by EvilBeaver** [comment]
Не жди, реализуй ))

**Comment by nixel2007** [comment]
Разве это не смешение обязанностей?

**Comment by nixel2007** [comment]
хотя если рассматирвать логос как форматтер выводимых строк...

Лично меня смущает то, что функция **вывода** строки в консоль дополнительно как-то модифицирует входящую строку (помимо того, что установлено методом УстановитьРаскладку).

**Comment by EvilBeaver** [comment]
@nixel2007 я не уловил - а где тут "модификация входящей строки"? И это не функция вывода в консоль, а функция логирования. В ней интерполяция строк выглядит вполне уместно, имхо.

**Comment by artbear** [comment]
Проверить поведение ночной сборки 1скрипт по https://github.com/EvilBeaver/OneScript/issues/269 и затем переделать код текущего issue

**Comment by EvilBeaver** [comment]
Предлагаю оптимизацию: если доп. параметров не передавали, то не вызывать вхолостую СтрШаблон, чтобы не снижать производительность логирования.

**Comment by artbear** [comment]
Переоткрою до появления ночной сборки oscript, исправляющей баг https://github.com/EvilBeaver/OneScript/issues/269
