### ISSUE TITLE
[gitsync] Документировать командную строку для всех команд и параметров

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#109]
- [x] Указать параметры командной строки для каждой из команд
- [x] Указать примеры использования
- [x] Для каждой из команд:
  - [x] init
  - [x] clone
  - [x] all
  - [x] set-version
  - [x] export
  - [x] help

**Comment by EvilBeaver** [comment]
@artbear ты вроде это уже сделал? Поставишь флажки что есть/чего нет?

**Comment by artbear** [comment]
Да, сделано.
