### ISSUE TITLE
gitsync: Помещать файлы авторов/версий в нужный подкаталог создаваемого репозитария Git

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#112]
Важно для сценария `в одном репозитарии Git хранятся как исходники конфигурации 1С, так и прочие исходники/файлы продукта (например, документация, тесты и прочее)`

Шаги, приводящие к ошибке:

```
1. Создаю локальный каталог для репозитария гит
2. Инициализирую в нём `gitsync init d:\data src/config`
4. тогда создаётся свой отдельный репозитарий git внутри моего будущего репозитария, что неверно

  data\
    |src\
        |config\
            |.git
```

В дополнение к #82

**Comment by artbear** [comment]
Вместо текущего поведения
1. сd src\config 
2. git init
3. создание файлов авторов и версий в этом каталоге

хочется правильного:
1. git init
2. сd src\config
3. создание файлов авторов и версий в этом каталоге

**Comment by realMaxA** [comment]
Текущее поведение команды корректно.
Сравните:

```
mkdir git-repo-1
cd git-repo-1
git init
mkdir git-repo-2
cd git-repo-2
git init
```

В данном случае происходит ровно то же самое.

**Comment by nixel2007** [comment]
@realMaxA некорректно. второй репозиторий не нужен.

**Comment by realMaxA** [comment]
Прошу очень внимательно отнестись к моему сообщению. Это **нормальное** поведение безотносительно того, нужен второй репозитарий или нет. Аналогию я привёл, изучите её.

**Comment by artbear** [comment]
@realMaxA Прав @nixel2007 
Для гита это поведение верно, для нашего продукта нет.
Мы не должны создавать еще один внутренний репозитарий, если мы знаем о наличии существующего репозитария

**Comment by artbear** [comment]
А гит соответственно ничего не знает, что где-то на верхнем уровне есть репозитарий, и потому его поведение абсолютно нормально.

**Comment by EvilBeaver** [comment]
@artbear git умеет в большинстве команд понимать, что на верхнем уровне есть репозитарий. Это в односкриптовом коде менять надо обработку

**Comment by artbear** [comment]
@EvilBeaver про гит согласен, главное, что код гитсинк нужно менять, поэтому и создана эта задача

**Comment by realMaxA** [comment]
Параметр <ЛокальныйКаталогГит> подразумевает указание расположения **git**-репозитария в файловой системе. Он обязан быть **корнем** git-репозитария.
Если исходники нужно класть в какой-то подкаталог текущего репозитария, нужно вводить **новый** параметр.

**Comment by artbear** [comment]
Про новый параметр согласен.

**Comment by EvilBeaver** [comment]
СТОП!
Параметр, может быть неудачно назван, но везде в коде он интерпретируется, как "Каталог в котором лежат исходники и файл VERSION". В команде init это не так. НО я вообще сомневаюсь в необходимости команды init. С ней только путаница. Она должна создать нужные файлы и все. Не надо ей, имхо, вообще иметь дел с механикой git-а

**Comment by realMaxA** [comment]
Именно

**Comment by realMaxA** [comment]
> но везде в коде он интерпретируется, как "Каталог в котором лежат исходники и файл VERSION"

Самое простое решение, это отказаться от `git init` и `git clone` в gitsync (т. е. `gitsync clone` совсем отмирает), и будет счастье.
Но это не в полной мере решит проблему со сложностью освоения.

Потому, что при `gitsync init` ничего не говорится про git-репозитарий, но `gitsync sync`, при этом делает и commit и push, т. е. репозитарий всё-таки подразумевается. Здесь наблюдается разрыв.

**Comment by EvilBeaver** [comment]
Господа, я не спроста завел #82 
Там приведен сценарий, как может быть. Он не идеален. Правьте должный сценарий, а реализация вторична уже. В частности, данная issue - попадает в сценарий из #82?

**Comment by realMaxA** [comment]
Данная issue вообще не нужна.

**Comment by EvilBeaver** [comment]
@artbear ?

**Comment by artbear** [comment]
Сейчас есть обозначенный баг для текущей реализации. Поэтому задача нужна.

Если мы выберем другое поведение, которое сейчас обсуждается в гиттер, то сделаем новую задачу, новую реализацию и новый релиз.

Все остальные задачи по гитсинку после выпуска нового релиза можно будет поправить (удалить, отменить) в соответствии с тем, нужна задача в новом поведении или нет.

**Comment by EvilBeaver** [comment]
подниму. Что с задачей?

**Comment by realMaxA** [comment]
Сейчас появилось небольшое окно, пытаюсь нарисовать фичи. Опыта совсем не хватает.
При благоприятном стечении обстоятельств сегодня дорисую в _каком-то_ виде. Нужно будет доводить до ума.

**Comment by realMaxA** [comment]
Всё, что успел на сегодня. Я совсем не понимаю, как описать опции, особенно опции по умолчанию (и нужно ли?). В общем прошу помощи для приведения этих фич в приемлемый вид.

[features.zip](https://github.com/EvilBeaver/oscript-library/files/341700/features.zip)

**Comment by artbear** [comment]
@realMaxA Спасибо за фича-файлы.

Предлагаю тебе сделать пулл-реквест в проект, добавив файлы фич в каталог gitsync\features

В этом PR и сможет обсудить конкретные детали конкретных фич и предложения по их доработке.

Что скажешь?

**Comment by realMaxA** [comment]
src/gitsync/features?
да, сделаю. Заодно узнаю, что это такое )

**Comment by artbear** [comment]
Реализовано через BDD-фичи проекта https://github.com/artbear/1bdd
