### ISSUE TITLE
Библиотека для парсинга v8i и очистки кеша баз

### ISSUE THREAD

**Issue by ret-Phoenix** [EvilBeaver/oscript-library#114]
parserV8i.os:
- ПолучитьСписокБаз - возвращает Соответствие со списком баз, где: Ключ - Имя базы, Значение  Структура с параметрами базы;
- ЗаписатьСписокБаз - Записывает список баз в файл, как источник принимается результат от ПолучитьСписокБаз

clearCash.os:
    Значения параметров
- all: удалить весь кеш (для баз прописанныхв в файле v8i)
- P "<ПутьКБазе>": удалить кеш базы. Строки с пробелами заключать в кавычки (P "c:\work\db\My path\"). Следует обратить 2 слеш на конце.

https://github.com/ret-Phoenix/ini_parse

**Comment by EvilBeaver** [comment]
не нашел, как именно она подключается. Можете привести пример кода, который ее использует?

**Comment by artbear** [comment]
@EvilBeaver Я уже пообщался с Сергеем, подсказал, как добавить указание классов, чтобы можно было использовать продукт в режиме библиотеки.

**Comment by EvilBeaver** [comment]
Ну и название тогда уже не ini-parse, а какое-то более конкретное, соответствующее назначению библиотеки

**Comment by ret-Phoenix** [comment]
Изначально это был форк, теперь же переписал полностью, от оригинала не осталось даже 1 строки. сегодня/завтра сделаю на уровне классов и прицеплю тесты. Спасибо Артуру, подсказал как сделать.

**Comment by ret-Phoenix** [comment]
Обновил. Перевел все на классы, добавил примеры работы.

**Comment by JohnyDeath** [comment]
А пул-реквест в этот репо не делал?

**Comment by ret-Phoenix** [comment]
Пока нет, первый опыт. Как будет время у EvilBeaver, надеюсь глянет

**Comment by EvilBeaver** [comment]
Все в одном репо - это неудобно. я завел отдельную организацию, буду туда мигрировать. Новые пакеты будут жить там. https://github.com/oscript-library

**Comment by pumbaEO** [comment]
ооо, так что будешь git filter-branch баловатьcя?

**Comment by EvilBeaver** [comment]
@pumbaEO судя по тому, что я не знаю что это такое - нет, не буду :smile:

**Comment by pumbaEO** [comment]
@EvilBeaver  это что-бы всю историю по каждому отдельному каталогу перенести в отдельный репозитарий, дабы не начинать с чистого листа.

**Comment by ret-Phoenix** [comment]
Пересоздал репозиторий: https://github.com/ret-Phoenix/parserV8i (чтобы отвязаться от мертвого проекта с которого изначально был сделан форк)

**Comment by EvilBeaver** [comment]
> что-бы всю историю по каждому отдельному каталогу перенести в отдельный репозитарий, дабы не начинать с чистого листа.

@pumbaEO дада, хочу!

**Comment by EvilBeaver** [comment]
@ret-Phoenix я клонировал новый репо в организацию library. В ближайшее время постараюсь этот пакет собрать и выложить в хаб
