### ISSUE TITLE
gitsync: Добавлять в коммит только файлы конфигурации

### ISSUE THREAD

**Issue by JohnyDeath** [EvilBeaver/oscript-library#116]
На текущий момент gitsync делает коммит по всем файлам, которые располагаются в каталоге git-репозитория.
В моем случае было так.
Имею репозиторий в каталоге Repo
Работал над документацией в каталоге repo\docs
Фоном запустилась синхронизация с хранилищем в каталог repo\src\config
В итоге на git-сервер улетели мои недоделки по документации, которые я хотел закоммитить отдельно.

**Comment by EvilBeaver** [comment]
Ты работал в той же рабочей копии, что и синхронизатор. Это неверно идеологически. Каждому пользователю - своя рабочая копия. Тогда и ситуаций таких не будет

**Comment by JohnyDeath** [comment]
а нельзя в git add указать конкретно папку repo/src/config ?
Я пока не могу себе позволить иметь под каждую задачу отдельную машину

**Comment by nixel2007** [comment]
@JohnyDeath можно :)
Андрей говорит не про отдельную машину. достаточно распаковку натравить на другой каталог.

**Comment by EvilBeaver** [comment]
Поясню: синхронизатор работает с копией исходников в папке А. Ты в этой папке ничего не трогаешь, представь, что она вообще от тебя закрыта правами. Ты себе делаешь отдельный clone. И вот в нем делаешь, что хочешь. Тогда конфликтов не будет.

**Comment by JohnyDeath** [comment]
@nixel2007 я знаю, что можно. Спрашивал именно про то, почему бы в gitsync-е так не сделать.
Есть какие-то принципиальные ограничения/конфликты?

**Comment by nixel2007** [comment]
@JohnyDeath ты можешь быть не в девелоп ветке. Или откатанным по истории назад

**Comment by nixel2007** [comment]
Да и измененные, но незакомиченные файлы могут дать конфликт при пуле

**Comment by JohnyDeath** [comment]
ок, понял, спасибо.
Значит буду мутить разграничивать каталоги для основной работ и для синхронизации хранилища
