### ISSUE TITLE
Использовать иерархическую выгрузку 8.3.7

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#12]
1.В связи с появлением иерархической выгрузки в 8.3.7 лучше использовать именно ее.
2. Текстовые файлы конфигурации должны иметь расширение bsl вместо txt

**Comment by EvilBeaver** [comment]
@pumbaEO правильно я понимаю, что этот тикет можно закрыть?

**Comment by pumbaEO** [comment]
Да.
