### ISSUE TITLE
Фильтр игнорируемых файлов

### ISSUE THREAD

**Issue by Gamms** [EvilBeaver/oscript-library#120]
Возникла проблема - почему то при выгрузке хранилища пять макетов печатных форм (Template.xml) всегда считаются как измененные. При этом изменений никаких в них не было. 
![image](https://cloud.githubusercontent.com/assets/19993893/16373945/05c0534c-3c5d-11e6-8f1a-819f5653f3ca.png). Строки с изменениями всегда одни и теже.
Может кто сталкивался с подобной ошибкой? Возможно это некорректная работа сравнения.
Сейчас у меня только один вариант решения - добавить эти файлы в .gitignore, но хотелось бы разобраться с причиной.

**Comment by nixel2007** [comment]
Это некорректная работа выгрузки из 1с. Если используется последняя версия платформы - добро пожаловать на v8@1c.ru
Если не последняя - то обновляйтесь :)

**Comment by EvilBeaver** [comment]
@nixel2007 а они что, это уже решили?

**Comment by nixel2007** [comment]
@EvilBeaver мой посыл был про то, что если это на последней версии платформы, то надо пинать 1с. если не на последней, то попробовать обновиться, может в последствии уже исправили.

**Comment by EvilBeaver** [comment]
@Gamms по моей информации это не исправлено. Для "отката" таких вот ненужных модификаций применяется скрипт undiff от @pumbaEO 

https://github.com/pumbaEO/undiff1c

Насчет того, как его правильно применять - также к @pumbaEO
