### ISSUE TITLE
gitsync: Добавить режим выгрузки без привлечения v8unpack

### ISSUE THREAD

**Issue by dammanapov** [EvilBeaver/oscript-library#122]
Насколько я понимаю v8unpack используется для разбора обычных форм.

Сейчас обычно работа ведется с управляемыми и было бы здорово иметь возможность выбирать нужно ли разбирать обычные.

Проблема возникает с временем выгрузки базы. Обычная выгрузка в моем примере ~3.5 часа, без v8unpack около 40 минут.

База нетиповая большая и с длинной историей, вся работа в части разработки практически полностью в управляемых формах, слишком большой оверхед получается с разбором обычных форм для объектов которые практически никогда не меняются

**Comment by EvilBeaver** [comment]
Правильно ли я понял, что у вас все-таки есть обычные формы, просто они не меняются?

Но тогда как gitsync может понять менялись они или нет? Для этого нужно их все равно разобрать. Иначе коммит рискует быть неполным. Кажется, что проблема чуть глубже, чем просто отключение v8unpack....

**Comment by dammanapov** [comment]
Да, верно. Формы обычные но они не меняются.
gitsync действительно не может понять менялись они или нет но хотелось бы иметь возможность сказать что я готов пожертвовать изменениями обычных форм ради производительности и, в этом случае, не разбирать их

**Comment by alexkmbk** [comment]
Не знаю где можно спросить, спрошу здесь, топик вроде бы подходящий. Данный проект не поддерживает управляемые формы? То есть только можно распаковывать конфигурации написанные для обычных форм?

**Comment by EvilBeaver** [comment]
Можно любые. А спрашивать можно в чате gitter. Ссылка в ридми на главной странице

**Comment by alexkmbk** [comment]
Спасибо! Ссылку на чат увидел
