### ISSUE TITLE
gitsync: В случае установки ключа -debug в "on" устанавливать уровень логов "Отладка"

### ISSUE THREAD

**Issue by dammanapov** [EvilBeaver/oscript-library#123]

**Comment by EvilBeaver** [comment]
Он вроде как и должен так устанавливаться. @artbear, мы это сломали?

**Comment by artbear** [comment]
Исправлено.
Моя ошибка - требование по debug у нас было "размыто" в #65, я его и пропустил :(

**Comment by EvilBeaver** [comment]
@artbear спасибо!
