### ISSUE TITLE
opm: Командный файл скрипта, сгенерированный через opm app, не возвращает код возврата от скрипта в системе

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#136]
Сейчас код создаваемого командного файла следующий

```
@echo off
oscript.exe "C:\Users\a_ayukhanov\Documents\projects\1bdd\src\bdd.os" %*
```

А правильно 

```
@oscript.exe "C:\Users\a_ayukhanov\Documents\projects\1bdd\src\bdd.os" %*
@exit /b %ERRORLEVEL%
```

**Comment by artbear** [comment]
@pumbaEO @dmpas Подскажите, существует ли подобная проблема в Linux ?

**Comment by dmpas** [comment]
@artbear там другая беда (https://github.com/EvilBeaver/oscript-library/issues/137)
а с кодом возврата всё хорошо.

**Comment by EvilBeaver** [comment]
Мне казалось что батник и так автоматом вернет код последней выполнившейся команды. Вручную возвращать errorlevel никогда не требовалось, имхо

**Comment by artbear** [comment]
Я проверил, не возвращает :(
Поэтому пришлось добавить

вс, 24 июл. 2016 г. в 22:16, Andrei Ovsiankin notifications@github.com:
