### ISSUE TITLE
opm app под линукс выдаёт неверный скрипт

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/oscript-library#137]
Лишняя кавычка ввыводится

```
ФайлЗапуска.ЗаписатьСтроку("oscript """ + ПутьФайлаПриложения + """ """"$@""");
                                                                    ^^
```

https://github.com/EvilBeaver/oscript-library/blob/develop/src/opm/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%B0.os#L315

**Comment by EvilBeaver** [comment]
На линуксе не тестил от слова вообще. Запилите кошерный пулреквест, кто может, а?

**Comment by dmpas** [comment]
@EvilBeaver таки вот: https://github.com/EvilBeaver/oscript-library/pull/138
