### ISSUE TITLE
Вопрос: Организация библиотек

### ISSUE THREAD

**Issue by theshadowco** [EvilBeaver/oscript-library#139]
Столкнулся с проблемой, прошу помощи.
Есть Библиотека, содержащая Модуль (src/core/Модули/Модуль.os) и Класс (src/core/Классы/Класс.os) + Скрипт (src/script.os).
В скрипте используется команда "#Использовать "core"".

Все работает, пока я не захочу использовать методы Модуля в Классе. Класс модули конечно же не видит, следовательно необходимо прописать "Использовать "../core/Модули"" В этом случае происходит ошибка "Невозможно загрузить модуль Модуль. Такой символ уже определен."

Создание файла lib.config, package-loader.os не помогает.

Выход пока один, вынесение Модуля в отдельную библиотеку, но это мне кажется неверным.

**Comment by theshadowco** [comment]
По сути нехватает #IFDEF ... #ENDIF

**Comment by EvilBeaver** [comment]
Модули загружаются первее и видят друг-друга. Классы загружаются позже и видят модули. Использование модуля в классе должно работать. Можете прислать пример, воспроизводящий ошибку?

**Comment by theshadowco** [comment]
[demo.zip](https://github.com/EvilBeaver/oscript-library/files/385343/demo.zip)
Во вложении демо-либа
- если я компилирую класс (проверяю его в VSC) - работает
- если я компилируюскрипт - ошибка
- если я удаляю строку "#Использовать "../Модули"" в классе - скрипт работает, но класс при самостоятельной проверке выдает ошибку

**Comment by theshadowco** [comment]
Возможно это ошибка именно VSC и вопрос к плагину

**Comment by nixel2007** [comment]
> Возможно это ошибка именно VSC и вопрос к плагину

Запуск производится штатной командой `oscript -encoding=utf-8 path/to/os/file`, при этом текущий рабочий каталог установлен корнем проекта.

**Comment by theshadowco** [comment]
> Запуск производится штатной командой oscript -encoding=utf-8 path/to/os/file, при этом текущий рабочий каталог установлен корнем проекта.

@nixel2007 при сохранении модуля такое же поведение?

**Comment by nixel2007** [comment]
@theshadowco 

> @nixel2007 при сохранении модуля такое же поведение?

при сохранении модуля не отрабатывает запуск скрипта, только `oscript -encoding=utf-8 check path/to/os/file`. CWD всегда корень проекта. Если задана настройка language-1c-bsl.linterEntryPoint, то дополнительно передается параметр `-env`

**Comment by EvilBeaver** [comment]
@theshadowco я так и не понял, речь идет о проверках внутри VSC, или скрипт реально не запускается на выполнение и выдает ошибку компиляции?

**Comment by theshadowco** [comment]
@EvilBeaver 
1. если выполнять проверку / компиляцию в VSC Класса без указания пути к модулям - не видит (понятно почему, спасибо за разъяснение  @nixel2007), если компилить скрипт, то он видит и модули и класс
2. если сделать чтобы класс компилился (прописать Использовать), то он проходит проверку / компиляцию в VSC, но перестает компилится скрипт (но в VSC он проверку все равно проходит нормально).

**Comment by EvilBeaver** [comment]
@theshadowco поясни, пожалуйста, еще раз. Я скачал архив demo.zip.

Куда я должен нажать и что запустить, чтобы увидеть ошибку?

**Comment by theshadowco** [comment]
@EvilBeaver Сорри за задержку в ответе, завал.

Итак, 
вариант как есть 
- если в VSC скомпилить (ctrl+shift+B) скрипт.os - выдаст ошибку. 
- если в VSC скомпилить  / проверить Классы/Класс1.os - работает 

вариант исправляем ошибку скрипта, для чего комментируем строку `#Использовать "../Модули"` в файле Классы/Класс1.os
- если в VSC скомпилить (ctrl+shift+B) скрипт.os - работает
- если в VSC скомпилить  / проверить Классы/Класс1.os - выдает ошибку

**Comment by artbear** [comment]
@theshadowco Из твоих ответов увидел, что ошибка есть во всех случаях.
Но задачу ты закрыл?
Проблема есть или нет в итоге?

**Comment by theshadowco** [comment]
@artbear  не люблю висяки. 

В принципе есть следующая ишуза, https://github.com/EvilBeaver/oscript-library/issues/161, с предложением о приватных модулях в камменте. Если получится, то упомянутая здесь проблема тоже уйдет.
