### ISSUE TITLE
Работа opm через proxy

### ISSUE THREAD

**Issue by realMaxA** [EvilBeaver/oscript-library#145]
При попытке установки пакета в сети, закрытой брандмауером, возникает ошибка:

```
Внешнее исключение: The remote name could not be resolved: 'hub.oscript.io'
```

т. к. закрыты все порты, в том числе и 53. Для возможности использования интернет организован proxy сервер.

Нужна возможность указать opm параметры proxy и обеспечить возможность работы opm через указанный proxy.

**Comment by EvilBeaver** [comment]
Дубликат #105
