### ISSUE TITLE
Добавить внешний реп messenger

### ISSUE THREAD

**Issue by theshadowco** [EvilBeaver/oscript-library#153]
Добавиьт в состав библиотеки репозиторий https://github.com/oscript-library/messenger, ранее он там был

**Comment by EvilBeaver** [comment]
Он переехал в библиотеку. В стандартной поставке вообще должен остаться минимум. В теории, даже гитсинк оттуда надо удалить.

**Comment by theshadowco** [comment]
Тогда стоит явно сформировать библиотеку а-ля stdlib и как-то прописать правила/требования, что может быть включено в стандартную библиотеку, а что нет.
