### ISSUE TITLE
ошибка клонирования с подмодулями

### ISSUE THREAD

**Issue by ghost** [EvilBeaver/oscript-library#156]
https://github.com/EvilBeaver/oscript-library/blob/develop/.gitmodules#L24

при клонировании с подмодулями получаем ошибку

> Command "C:\Program Files\Git\bin\git.exe submodule update src/files-common" returned status code 1:
> stdout: 
> stderr: error: pathspec 'src/files-common' did not match any file(s) known to git.
> 

проблема кроется видимо в наименовании папки и наименовании подмодуля - они различаются

```
[submodule "src/files-common"]
	path = src/fs
```

**Comment by pumbaEO** [comment]
Это проблема только jenkins. гит сам нормально делает checkout

13 груд. 2016 р. 7:15 пп "Alexey Lustin" <notifications@github.com> пише:

**Comment by ghost** [comment]
@pumbaEO я починил - нужно просто наименование подмодуля указывать равным path

**Comment by ghost** [comment]
закрываю - смерджилось
