### ISSUE TITLE
Добавить автодокументирование параметров в cmdline

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/oscript-library#16]
Сделать, чтобы автоматически формировалось описание возможных ключей командной строки по их описанию.

**Comment by EvilBeaver** [comment]
Сделано получение объектной модели 69ba6368c

TODO: Сделать форматирование и вывод в консоль

**Comment by artbear** [comment]
Не забывай в тексте коммита ставить номер задачи #16 для автосвязки коммит и задачи :)
