### ISSUE TITLE
Обеспечить простую инсталляцию в PATH скриптов-стартеров для приложений

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/oscript-library#17]
Сейчас gitsync и opm генерируют bat/sh при установке через opm из пакета. А вот если opm не установлен в PATH, то сгенерировать bat/sh сложнее.

Нужен простой способ создания shell скрипта-стартера в PATH.

**Comment by artbear** [comment]
Совместно с @EvilBeaver пришли к варианту вызова:
`opm app script.os [folder]`

Заприложенить! (с) @EvilBeaver

**Comment by artbear** [comment]
Поправил строку запуска `opm app script.os [folder]`

**Comment by artbear** [comment]
нужно добавить к opm функциональность, чтобы можно было сгенерить bat-файл в указанной папке (folder) или КаталогПрограммы (если папка не указана) 
со следующим текстом 
`oscript.exe ПутьСкрипта\Скрипт.os  %*`

**Comment by artbear** [comment]
Код генерации уже есть в файле `oscript-library\src\opm\src\Классы\УстановкаПакета.os` - `СгенерироватьСкриптыЗапускаПриложенийПриНеобходимости`
Нужно только добавить параметры командной строки, обработать ком.строку, вызвав этот метод.

**Comment by artbear** [comment]
@EvilBeaver Добавляй в доку на сайте на opm описание генерации скрипта через `opm app script.os [folder]`
или дай мне возможность добраться до документации на сайте :)

**Comment by EvilBeaver** [comment]
@artbear напиши markdown с документацией, я всталю. Дать доступ там не так просто, там все неавтоматизировано, ручками и все сложно.. Сделаешь доку или набросок хотя бы?
