### ISSUE TITLE
Добавить gitrunner как сабмодуль в стандартной либе

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/oscript-library#172]

**Comment by artbear** [comment]
Как сабмодуль гита или как поставляемая библиотека в поставке движка?

**Comment by nixel2007** [comment]
Ну в хедере же все написано :) поставка движка собирается из сабмодулей этого репа. Поэтому надо добавить сабмодулем в этот реп, чтобы оно уехало с поставкой движка

**Comment by pumbaEO** [comment]
#174
