### ISSUE TITLE
Нужна статья про то, как создать компоненту средствами 1Скрипта, а не C#

### ISSUE THREAD

**Issue by ArsenShnurkov** [EvilBeaver/oscript-library#179]
Неясно, как это сделать (и можно ли), http://oscript.io/dev/page/components

Вроде бы компонента/библиотека начинается с файла package-loader.os - 
http://oscript.io/docs/page/libraries

кроме того, есть (http://oscript.io/library) заманчивая картинка
<img src="http://oscript.io/Content/images/lib_convention.png" />

Но всё вместе оно как-то не складывается в голове, как надо что писать и куда класть в файловой системе.

**Comment by nixel2007** [comment]
В планах на ближайший месяц-два. Либо одна большая - как сделать библиотеку и как сделать приложение, либо две поменьше.

**Comment by nixel2007** [comment]
> как это сделать (и можно ли)

большинство библиотек написаны на oscript, а не на c# :)

**Comment by bambr1975** [comment]
https://infostart.ru/public/548028/ раздел "Схема загрузки библиотек", плюс уже упомянутый http://oscript.io/docs/page/libraries плюс https://github.com/oscript-library/oscript-lib-template и https://github.com/oscript-library/oscript-app-template

**Comment by ArsenShnurkov** [comment]
Простой вопрос - чем "классы" отличаются от "модулей"? У них какой-то особый синтаксис? Где этот синтаксис описан?

**Comment by bambr1975** [comment]
http://oscript.io/docs/page/package-loader
Под классом понимается новый тип в системе типов приложения. Экземпляры объектов этого типа создаются через оператор Новый.
  Модуль это то же самое, что ОбщийМодуль в системе 1С:Предприятие. Модуль - это свойство в глобальном контексте, методы которого мы можем вызывать из языка.

**Comment by ArsenShnurkov** [comment]
я имею в виду синтаксис в месте определения класса, а не в месте использования через оператор Новый

**Comment by nixel2007** [comment]
Классы инстанцируются с помощью оператора Новый. Каждый инстанс имеет свои собственные версии глобальных переменных скрипта.
Модули инстанцируются при начале работы приложения, как общие модули конфигурации. Глобальные переменные таких модулей (если они есть) общие на все время выполнения

**Comment by nixel2007** [comment]
у класса еще есть необязательный метод ПриСозданииОбъекта.

различий в синтаксисе описания классов и модулей нет, т.к. этого не позволяет сама грамматика 1С

**Comment by ArsenShnurkov** [comment]
в языке C# для класса есть ключевое слово "class", есть ли подобное в 1Скрипт? Или класс отличается от модуля только тем, что в классе описаны переменные в глобальном скопе, а в модуле не описаны?

**Comment by nixel2007** [comment]
> в языке C# для класса есть ключевое словл "class", есть ли подобное в 1Скрипт?

нет, такого нет. все различие - в способе инстанцирования.

**Comment by nixel2007** [comment]
> Или класс отличается от модуля только тем, что в классе описаны переменные в глобальном скопе, а в модуле не описаны?

в модуле тоже могут быть переменные в глобальном скоупе.

**Comment by EvilBeaver** [comment]
@ArsenShnurkov все как на картинке. Будет файл "классом" или "модулем" зависит от того, в какой папке он лежит. Внутри синтаксически они не отличаются никак.

Если копнуть еще глубже, то дело не в папках, а в алгоритме модуля package-loader.os. Именно он решает в какую из групп "класс"/"модуль" отнести тот или иной файл .os

**Comment by bahtiy** [comment]
ArsenShnurkov, напишите, пожалуйста на почту bahtiev@mail.ru или дайте Ваш контакт. Извиняюсь за оффтоп. Не нашел никакого другого средства коммуникации.

**Comment by ArsenShnurkov** [comment]
>.Не нашел
и мне кажется, что это хорошо, уважаемый Бахтиев Эдуард Маратович,  24.06.1988, закончивший 11Б лицея 131 и Казанский национальный исследовательский технический университет им. А. Н. Туполева (КАИ), работающий в ООО "ПрофТехСтрой"  директором по Московскому региону, c телефоном 8-926-667-35-00

**Comment by bahtiy** [comment]
Здравствуйте. Если Вы владелец брошенного аккаунта  https://bitcointalk.org/index.php?action=profile;u=3386   , то прошу рассмотреть возможность продажи/передачи в аренду.

Пост удалил.

**Comment by bahtiy** [comment]
Тут половина уже не актуальна) Напишите, пожалуйста, на bahtiev@mail.ru

**Comment by EvilBeaver** [comment]
@bahtiy - это к кому просьба? Про написать?

**Comment by ArsenShnurkov** [comment]
У этого человека есть лишние деньги. Он думает, что его деньги кому-то нужны и могут на что-то повлиять. Думаю, можно присылать ему инвестиционные предложения.

**Comment by EvilBeaver** [comment]
Ничо не понял

**Comment by ArsenShnurkov** [comment]
Ничего не получается.

```
// Файл main.os
#Использовать Classes
    
Перем символ;
символ = Новый Символ();
символ.Выступить_С_Речью();
```

```
// Файл oscript.cfg
lib.additional = .;
```

```
// Файл package-loader.os
ДобавитьКласс("./Classes/symbol.os", "Символ");
```

```
// Файл Classes/symbol.os
Процедура ПриСозданииОбъекта()
КонецПроцедуры
Процедура Выступить_С_Речью() Экспорт
	Перем консоль;
	консоль = Новый Консоль();
	консоль.ВывестиСтроку("за роботу товарещи");
КонецПроцедуры
```

Результат:

    {Модуль main.os / Ошибка в строке: 5 / Ожидается идентификатор}

**Comment by ArsenShnurkov** [comment]
Так тоже не работает

```
// Файл main.os
Попытка
	ПодключитьСценарий("symbol.os","Символ");
	Высказать();
Исключение
	Сообщить("Пичаль/бида");
КонецПопытки;
```

```
// Файл symbol.os
Процедура Высказать() Экспорт
	Сообщение("за роботу товарещи");
КонецПроцедуры
```

Пишет

    {Модуль main.os / Ошибка в строке: 4 / Неизвестный символ: Высказать}


$ oscript -v | head -1
1Script Execution Engine. Version 1.0.19.0

есличё, новее релизов нет <a href="https://github.com/EvilBeaver/OneScript/releases">в списке тэгов репозитория</a>

**Comment by arkuznetsov** [comment]
@ArsenShnurkov :
// МойКласс.os
```bsl
Процедура ПриСозданииОбъекта()
	Сообщить("Создан класс!");
КонецПроцедуры

Процедура МойМетод() Экспорт
	Сообщить("Вызван метод");
КонецПроцедуры
```
//main.os
```bsl
ПодключитьСценарий("МойКласс.os", "МойКласс");

ЭкземплярКласса = Новый МойКласс();

ЭкземплярКласса.МойМетод();
```
вот так работает

**Comment by ArsenShnurkov** [comment]
Ясно, слово "Символ" неудачное было... Надо было использовать "СимволПрорыва"

**Comment by EvilBeaver** [comment]
Вопрос решен вроде бы

**Comment by EinstokFair** [comment]
Не затруднит ли Вас в таком случае добавить сюда ссылку на эту замечательную обучающую статью с официального сайта 1Скрипт, раз уж вопрос решен. Или таки не решен?

**Comment by nixel2007** [comment]
http://oscript.io/docs

Статья под заголовком "Исчерпывающее руководство по созданию библиотеки 1Script" ведет на мою статью на ИС.
