### ISSUE TITLE
Пакет обработки командной строки

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#2]
Пакет обработки командной строки
Пример командной строки:
    `oscript test.os --run --ИмяБазы "База1" --Пользователь "admin" --Пароль "123"`
    `oscript test.os run ИмяБазы "База1" Пользователь "admin" Пароль "123"`

Интерфейс:
- ДобавитьПараметр(ИмяПараметра)
- ДобавитьПараметрФлаг(ИмяПараметра)
- ДобавитьПараметрКоллекция(ИмяПараметра)
  - после ключа можно задавать любое количество значений до появления следующей команды или до конца строки
- Разобрать(ВходнойМассивПараметров)
  -- Возвращает соответствие

Пример теста:

```
    // строка запуска - oscript test.os Параметр Значение или oscript test.os "Параметр" "Значение"
    ВходнойМассивПараметров = Новый Массив;
    ВходнойМассивПараметров.Добавить("Параметр");
    ВходнойМассивПараметров.Добавить("Значение"); 

    ПарсерКомаднойСтроки.ДобавитьПараметр("Параметр");

    Коллекция = ПарсерКомаднойСтроки.Разобрать(ВходнойМассивПараметров); //АргументыКоманднойСтроки);

    юТест.ПроверитьРавенство(1, Коллекция.Количество());
    юТест.ПроверитьРавенство("Значение", Коллекция.Получить("Параметр"));
    юТест.ПроверитьРавенство("Значение", Коллекция["Параметр"]);
```

**Comment by EvilBeaver** [comment]
@artbear можем закрывать issue?

**Comment by artbear** [comment]
Нет, еще не реализованы следующие методы интерфейса:
- ДобавитьПараметрФлаг(ИмяПараметра)
- ДобавитьПараметрКоллекция(ИмяПараметра)
  - после ключа можно задавать любое количество значений до появления следующей команды или до конца строки

Можно создать 2 отдельные задачи по этим методам

**Comment by nixel2007** [comment]
Как-то у меня не получается использовать функцию ДобавитьПараметрФлаг().
Я правильно понимаю, что подразумевается добавление флага, используемого независимо от других типов параметров (в частности, именованных?). Если да, то не получается использовать его в такой реализации (на базе скрипта v8files-extractor.os из precommit):

```
Лог = Логирование.ПолучитьЛог("oscript.app.v8files-extractor");

Парсер = Новый ПарсерАргументовКоманднойСтроки();
Парсер.ДобавитьПараметрФлаг("--remove-orig-bin-files"); 

ДобавитьОписаниеКомандыДекомпилировать(Парсер);
ДобавитьОписаниеКомандыПомощь(Парсер);
ДобавитьОписаниеКомандыИзмененияПоЖурналуГит(Парсер);

Аргументы = Парсер.Разобрать(АргументыКоманднойСтроки);
```

Вызов с из TestApp с такими аргументами:

```
#Аргументы командной строки (по одному на строку)
--git-precommit
"фыв"
--remove-orig-bin-files
```

критует с

```
{Модуль C:\Program Files (x86)\OneScript\lib\cmdline\src\cmdline.os / Ошибка в строке: 198 / Ожидается наличие позиционного параметра}    
        ВызватьИсключение "Ожидается наличие позиционного параметра";
Error detected. Exit code = 1
Script completed: 22.10.2015 19:46:46
Duration: 00:00:00.0154706
```

Если же добавлять флаг как часть параметра `--git-precommit` через `Парсер.ДобавитьПараметрФлагКоманды(ОписаниеКоманды, "--remove-orig-bin-files");`, то все отрабатывает корректно, но тогда этот флаг нужно добавлять в каждую из "ВозможныеКоманды".

Версия библиотеки свежайшая, с develop.

**Comment by EvilBeaver** [comment]
ДобавитьПараметрФлаг еще только заявлен в задачах. Его нет в классе парсера.

-----Исходное сообщение-----
От: "Nikita Gryzlov" notifications@github.com
Отправлено: ‎22.‎10.‎2015 19:50
Кому: "EvilBeaver/oscript-library" oscript-library@noreply.github.com
Копия: "Andrei Ovsiankin" ovsiankin.aa@gmail.com
Тема: Re: [oscript-library] Пакет обработки командной строки (#2)

Как-то у меня не получается использовать функцию ДобавитьПараметрФлаг().
Я правильно понимаю, что подразумевается добавление флага, используемого независимо от других типов параметров (в частности, именованных?). Если да, то не получается использовать его в такой реализации (на базе скрипта v8files-extractor.os из precommit):
Лог = Логирование.ПолучитьЛог("oscript.app.v8files-extractor");

Парсер = Новый ПарсерАргументовКоманднойСтроки();
Парсер.ДобавитьПараметрФлаг("--remove-orig-bin-files"); 

ДобавитьОписаниеКомандыДекомпилировать(Парсер);
ДобавитьОписаниеКомандыПомощь(Парсер);
ДобавитьОписаниеКомандыИзмененияПоЖурналуГит(Парсер);

Аргументы = Парсер.Разобрать(АргументыКоманднойСтроки);
Вызов с из TestApp с такими аргументами:
#Аргументы командной строки (по одному на строку)
--git-precommit
"фыв"
--remove-orig-bin-files
критует с
{Модуль C:\Program Files (x86)\OneScript\lib\cmdline\src\cmdline.os / Ошибка в строке: 198 / Ожидается наличие позиционного параметра}  
        ВызватьИсключение "Ожидается наличие позиционного параметра";
Error detected. Exit code = 1
Script completed: 22.10.2015 19:46:46
Duration: 00:00:00.0154706
Если же добавлять флаг как часть параметра --git-precommit через Парсер.ДобавитьПараметрФлагКоманды(ОписаниеКоманды, "--remove-orig-bin-files");, то все отрабатывает корректно, но тогда этот флаг нужно добавлять в каждую из "ВозможныеКоманды".

**Comment by artbear** [comment]
> ДобавитьПараметрФлаг еще только заявлен в задачах. Его нет в классе парсера.

Уже есть, я вчера сделал коммит в ветку develop

@nixel2007 ты брал свежую версию из develop ? или использовал старую версию?

**Comment by artbear** [comment]
Выше по тексту коммиты отмечены.

**Comment by nixel2007** [comment]
@artbear Брал свежую версию сегодня около 12 часов по Москве. Как раз увидел коммиты и решил посмотреть

**Comment by nixel2007** [comment]
В версии 69ba636 ошибка разбора переместилась в строку (но смысл тот же)

```
{Модуль C:\Program Files (x86)\OneScript\lib\cmdline\src\cmdline.os / Ошибка в строке: 249 / Ожидается наличие позиционного параметра}    
        ВызватьИсключение "Ожидается наличие позиционного параметра";
Error detected. Exit code = 1
Script completed: 23.10.2015 13:01:38
Duration: 00:00:00.0161284
```

Полный код скрипта, который я запускаю в TestApp:

```
#Использовать cmdline

Перем Лог;
Перем КодВозврата;
Перем мВозможныеКоманды;

Функция ВозможныеКоманды()

    Если мВозможныеКоманды = Неопределено Тогда
        мВозможныеКоманды = Новый Структура;
        мВозможныеКоманды.Вставить("Декомпилировать", "--decompile");
        мВозможныеКоманды.Вставить("Помощь", "--help");
        мВозможныеКоманды.Вставить("ОбработатьИзмененияИзГит", "--git-precommit");

    КонецЕсли;

    Возврат мВозможныеКоманды;

КонецФункции
Процедура ДобавитьОписаниеКомандыДекомпилировать(Знач Парсер)
    ОписаниеКоманды = Парсер.ОписаниеКоманды(ВозможныеКоманды().Декомпилировать);
    Парсер.ДобавитьПозиционныйПараметрКоманды(ОписаниеКоманды, "ПутьВходящихДанных");
    Парсер.ДобавитьПозиционныйПараметрКоманды(ОписаниеКоманды, "ВыходнойКаталог");
    Парсер.ДобавитьКоманду(ОписаниеКоманды);
КонецПроцедуры

Процедура ДобавитьОписаниеКомандыПомощь(Знач Парсер)
    ОписаниеКоманды = Парсер.ОписаниеКоманды(ВозможныеКоманды().Помощь);
    Парсер.ДобавитьКоманду(ОписаниеКоманды);
КонецПроцедуры

Процедура ДобавитьОписаниеКомандыИзмененияПоЖурналуГит(Знач Парсер)

    ОписаниеКоманды = Парсер.ОписаниеКоманды(ВозможныеКоманды().ОбработатьИзмененияИзГит);
    Парсер.ДобавитьПозиционныйПараметрКоманды(ОписаниеКоманды, "ВыходнойКаталог");
    //Парсер.ДобавитьПараметрФлагКоманды(ОписаниеКоманды, "--remove-orig-bin-files");
    Парсер.ДобавитьКоманду(ОписаниеКоманды);

КонецПроцедуры


Лог = Логирование.ПолучитьЛог("oscript.lib.cmdline");
Лог.УстановитьУровень(УровниЛога.Отладка);

Парсер = Новый ПарсерАргументовКоманднойСтроки();
Парсер.ДобавитьПараметрФлаг("--remove-orig-bin-files"); 

ДобавитьОписаниеКомандыДекомпилировать(Парсер);
ДобавитьОписаниеКомандыПомощь(Парсер);
ДобавитьОписаниеКомандыИзмененияПоЖурналуГит(Парсер);

Аргументы = Парсер.Разобрать(АргументыКоманднойСтроки);

Команда = Аргументы.Команда;
Лог.Отладка("Передана команда: "+Команда);
Для Каждого Параметр Из Аргументы.ЗначенияПараметров Цикл
    Лог.Отладка(Параметр.Ключ + " = " + Параметр.Значение);
КонецЦикла;
```

Если убрать `Парсер.ДобавитьПараметрФлаг("--remove-orig-bin-files");`  и раскомментировать `Парсер.ДобавитьПараметрФлагКоманды(ОписаниеКоманды, "--remove-orig-bin-files");` в `ДобавитьОписаниеКомандыИзмененияПоЖурналуГит`, то скрипт отрабатывает.

**Comment by artbear** [comment]
1. Есть 2 схемы работы с параметрами: просто произвольные параметры или одна команда со своими параметрами.

Если мы используем схему с командами, тогда использовать произвольные параметры нельзя. скрипт и выдает ошибку для этого случая. Нужно использовать именно параметры команды.
1. Вот и получается, что правильнее как раз перенести упоминаемый флаг как доп.параметр в команду `ИзмененияПоЖурналуГит`

**Comment by nixel2007** [comment]
@artbear Вооот оно что. Да, это действительно многое объясняет. Я бы добавил в справку по cmdline явное упоминание того, что можно использовать либо тот, либо иной режим (схему) работы.

**Comment by EvilBeaver** [comment]
@artbear @nixel2007 нет, можно использовать и режим команд и просто параметры совместно в одном вызове. Просто если передали команду (из известных), то метод "Разобрать" вернет структуру "Команда (строка),ЗначенияПараметров (соответствие)" А если передана не команда, то отработает, как обычные параметры и вернет Соответствие. Если эта схема не работает, то это ошибка.

**Comment by nixel2007** [comment]
@EvilBeaver Выше я привел кусок кода, на котором тестирую - я использую метод "Разобрать", и да, получаю ошибку.

**Comment by EvilBeaver** [comment]
Ок, значит это ошибка. Я к тому, что @artbear неверно написал. Можно использовать оба режима по задумке. @nixel2007 а какие именно параметры передаются? На каких входных данных спотыкается?

**Comment by artbear** [comment]
@EvilBeaver @nixel2007 ИМХО вы друг друга не поняли :(

@EvilBeaver 

> можно использовать и режим команд и просто параметры совместно в одном вызове. Просто если передали команду (из известных), то метод "Разобрать" вернет структуру "Команда (строка),ЗначенияПараметров (соответствие)" 

По примеру выше
для ком.строки `скрипт.os --git-precommit dir --remove-orig-bin-files` какая структура вернется??

**Comment by EvilBeaver** [comment]
@artbear по идее, должно вернуть структуру:
Команда = "--git-precommit"
ЗначенияПараметров = 
   ВыходнойКаталог="dir"
   --remove-orig-bin-files=true

**Comment by nixel2007** [comment]
@artbear по идее, должна вернуться структура
ключ: "--git-precommit"
значенияПараметров: Соответствие:
ключ: ВыходнойКаталог, значение: "dir"
ключ: "--remove-orig-bin-files", значение: Истина

Таким образом, в случае использования команд, флаг "--remove-orig-bin-files" должен добавляться в ЗначенияПараметров всех команд (если он передавался)

**Comment by nixel2007** [comment]
В концепции, описанной @EvilBeaver предполагается, что можно использовать команду + произвольные параметры (в том числе не флаги), я правильно понимаю?  
Т.е. если мы в парсер добавили описание команды И еще один общий, например, именованный параметр через `ДобавитьИменованныйПараметр` (не через `ДобавитьИменованныйПараметрКоманды`), то функция Разобрать() должна возвращать значение этого именованного параметра аналогично описанному выше способу с флагом?

[offtopic]
Количество слов "именованный" в предложении достигло критической отметки
[/offtopic]

**Comment by artbear** [comment]
Да

пт, 23 Окт 2015, 18:18, Nikita Gryzlov notifications@github.com:

**Comment by EvilBeaver** [comment]
Ну а в чем я не прав? Оно же так и работало еще до появления "флагов"

-----Исходное сообщение-----
От: "Artur Ayukhanov" notifications@github.com
Отправлено: ‎23.‎10.‎2015 19:10
Кому: "EvilBeaver/oscript-library" oscript-library@noreply.github.com
Копия: "Andrei Ovsiankin" ovsiankin.aa@gmail.com
Тема: Re: [oscript-library] Пакет обработки командной строки (#2)

Да 

пт, 23 Окт 2015, 18:18, Nikita Gryzlov notifications@github.com:

**Comment by artbear** [comment]
Реализован метод `ДобавитьПараметрФлаг`
