### ISSUE TITLE
opm.bat отсутствует в ночной сборке

### ISSUE THREAD

**Issue by pumbaEO** [EvilBeaver/oscript-library#22]
https://github.com/EvilBeaver/oscript-library/blob/develop/build/build-for-hub.os#L15

**Comment by pumbaEO** [comment]
т.е. при установке msi пакета, есть только oscript.exe, opm.bat нет.

**Comment by EvilBeaver** [comment]
Да, я в курсе, надо в CI добавить. Спасибо за issue!

**Comment by EvilBeaver** [comment]
Кстати, эта задача пересекается с #17

**Comment by EvilBeaver** [comment]
Исправлено в 1.0.12.17
