### ISSUE TITLE
Неверно обрабатывается директива !/usr/bin/oscript 

### ISSUE THREAD

**Issue by pumbaEO** [EvilBeaver/oscript-library#23]
bin\oscript.exe lib\opm\src\opm.os
{Модуль C:\Users\eugens\Downloads\OneScript-1.0.11(1)\lib\opm\src\opm.os / Ошибка в строке: 13 / Неизвестная директива: !(!/usr/bin/oscript)}

**Comment by EvilBeaver** [comment]
На какой версии?

**Comment by pumbaEO** [comment]
OneScript-1.0.11

**Comment by EvilBeaver** [comment]
А сборка?

**Comment by pumbaEO** [comment]
oscript.exe --version
1Script Execution Engine. Version 1.0.11.53

**Comment by EvilBeaver** [comment]
Странно, у меня вот так работает:
![](https://habrastorage.org/files/f45/8c3/1b4/f458c31b4c0c4dad9887fee872e82b55.png)

**Comment by EvilBeaver** [comment]
А opm, действительно, не работает. Там потому что BOM в начале стоит, скорее всего

**Comment by EvilBeaver** [comment]
убрал shebang совсем. Все равно строка запуска `opm.os install` некрасиво выглядела бы.
