### ISSUE TITLE
gitsync: при инициализации пустого репо создается все в папке src

### ISSUE THREAD

**Issue by pumbaEO** [EvilBeaver/oscript-library#24]
gitsync: при инициализации пустого репо создается все в папке src, при поптыке дальнейшей синхронизации не учитываеся что authors и version находится в подпапке src.

**Comment by EvilBeaver** [comment]
Здесь имелось в виду следующее:
КаталогРабочейКопии, как параметр функции, должен уже указывать на src. Т.е. репа может содержать не только конфу, но и тесты, документацию и прочее. gitsync должен получить путь, в котором указано где внутри репо лежат сорцы. Возможно, кто-то захочет хранить их в папке "Исходнеги", а не src, мы не можем диктовать.

А вот команда init делает инициализацию в стиле best-practices и намекает юзеру, что надо вот так строить репо - папочку src создать и в ней распаковывать.

Т.е. поведение было правильное. А вот документация этого, наверное не отражает. Хотелось бы услышать совет - где именно надо написать вот про это?

**Comment by pumbaEO** [comment]
В том то и проблема, что https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/src/gitsync.os#L240 у нас синхронизирует с корнем, при этом если указать с каталогом src, тогда этот код перестанет работать https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/src/gitsync.os#L234 

т.е. сейчас best-practices ломает все. Имхо, как bugfix это можно исправить и дополнительно создать feature для определения best-practices и что необходимо поменять.

**Comment by EvilBeaver** [comment]
@pumbaEO почему [git pull](https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/src/gitsync.os#L234) перестанет работать? я не догоняю..

**Comment by artbear** [comment]
@pumbaEO у нас все работает. я на боевых средах гоняю скрипт с последними
своими правками. нет проблем.

пт, 30 окт. 2015 г. в 16:46, Andrei Ovsiankin <notifications@github.com>:

**Comment by artbear** [comment]
@EvilBeaver я согласен с @pumbaEO, что при начальной инициализации у нас проблема.
Использование явного `src` в коде это лишнее, тем более, что `src` юзается только при инициализации, а вот при синхронизации юзается уже прямой каталог.

ИМХО нужно принимать пулл-реквест. Если у тебя нет возражений, я готов принять #25

**Comment by EvilBeaver** [comment]
Вся эта команда init нужна была для того, чтобы простимулировать создание правильной структуры каталогов. Без этого, исходники будут тупо положены в корень и все. Вообще, с учетом того, что есть vanessa-bootstrap, наверное, это и не страшно?
