### ISSUE TITLE
V8Runner ищет платформы только на диске C

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/oscript-library#30]
Места установки платформ нужно брать из служебного файлика 1С в %APPDATA%\бла-бла

Сейчас, если платформы ставятся не на диск C: v8runner их не сможет найти автоматом.

**Comment by nixel2007** [comment]
Дико плюсую. Полдня убил на то, что не получалось запустить конкретную версию платформы, пока не понял, что она у меня стоит на другом диске.

**Comment by EvilBeaver** [comment]
Дополню - надо выяснить про то, как происходит поиск платформ на линуксе

**Comment by vsuh** [comment]
А может,инициализировать класс без знания пути до исполняемого файла платформы, и сделать экспортную переменную `ПутьДоПлатформы1С` и если это свойство класса установлено, работать уже с ним.

**Comment by EvilBeaver** [comment]
@vsuh а оно так и работает, если я ничего не путаю. Класс инициализируется пустым, а полный путь до платформы можно задать явно вот так:

```
Конфигуратор.ПутьКПлатформе1С(ПолныйПутьКПлатформе);
```

**Comment by artbear** [comment]
@EvilBeaver да, именно так.

**Comment by vsuh** [comment]
```
        УК = Новый УправлениеКонфигуратором;
    УК.ПутьКПлатформе1С = "D:\Program Files (x86)\1cv8\8.3.6.2299\bin\1cv8.exe";
```

`{Модуль D:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 254 / Внешнее исключение: Не удалось найти часть пути "C:\Program Files (x86)\1cv8".}`

**Comment by artbear** [comment]
`УК.ПутьКПлатформе1С = "D:\Program Files (x86)\1cv8\8.3.6.2299\bin\1cv8.exe";`
так вообще неверно, это же метод, а не свойство.
правильно `УК.ПутьКПлатформе1С ( "D:\Program Files (x86)\1cv8\8.3.6.2299\bin\1cv8.exe" );`

**Comment by vsuh** [comment]
только что поставил на виртуалке 1С в e:\program files (x86)\1cv8\8.3.6.2299

```
 #use v8runner
 УК = Новый УправлениеКонфигуратором;
```

---

E:_ggg_\v8test>c:\progra~2\onescript\bin\oscript.exe ttt.os
{Модуль C:\Program Files (x86)\onescript\lib\v8runner\src\v8runner.os /
Ошибка в строке: 256 / Не найден путь к платформе 1С <8.3>}

5 ноября 2015 г., 19:15 пользователь Artur Ayukhanov <
notifications@github.com> написал:
