### ISSUE TITLE
Добавить версии для библиотек

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#34]
Добавить версии для библиотек, чтобы исключить в пользовательском коде комментарии  следующего вида `Требуется библиотека cmdline от 21.10.2015 и новее.`

Вопрос - какую архитектуру выберем?
Например, у каждого класса библиотеки будет метод Версия()?
или у каждой библиотеки будет глобальный метод Версия() ?
какие еще варианты есть?

@EvilBeaver что скажешь?

**Comment by dmpas** [comment]
оооо! добро пожаловать в ад!
учитывая, что последний коммит в мастер-ветке был ещё в сентябре, то зависимость "версия от 21.10.2015" выглядит очень удручающе.

**Comment by nixel2007** [comment]
так ведь уже есть версия в packagedef. Есть интерфейс по получению этой версии? Если да, то просто надо эту версию периодически бампить в самом packagedef.

**Comment by EvilBeaver** [comment]
Вопрос управления версиями библиотек был решен в стиле Руби - то есть на него решено было забить. В хранилище пакетов может стоять только одна версия какой-то библиотеки и все кто на нее ссылается по имени (а не по пути) будут использовать эту актуальную версию. Т.е. нельзя поставить lib1, lib2 и lib1.5 одновременно и чтобы система сама следила, какую версию для какого клиента подгрузить. Это не меньший ад, чем версионирование по датам.

dependency hell сейчас должен разрешаться пользователем. _Но!_  я сторонник минимизации усилий. Сейчас все библиотеки обратно совместимы сами с собой и, насколько мне известно, не требуется держать несколько версий одной и той же библиотеки. Если проблема возникнет, то тогда и можно будет, анализируя сценарий использования, ее решать.

Вопрос менеджмента версий нужно делать на основе манифеста в packagedef, и ни в коем случае не методом "Версия()" где бы то ни было.

В opm нет API для получения этой версии и я надеюсь на сообщество в доработке opm. Сейчас я выпал из обоймы, т.к. на работе некоторый завал (это можно видеть и по отсутствию меня в каментах и коммитах).

Итого, как всегда, начинать надо с user story - @artbear нужна четкая формулировка: для каких сценариев требуется фильтрация по версиям библиотек? В идеале - при установке программы, которая требует lib-1.5 opm должен сам обновлять текущую lib-1.1 до нужной версии.

**Comment by artbear** [comment]
Story: Сейчас некоторые наши скрипты, например, в precommit1C (и собственные/приватные) зависят от установленных библиотек.
У меня, например, скрипты работают на билд-агентах, которые находятся на разных машинах.
При обновлении скрипта библиотеки автоматом не обновляются.
в итоге при запуске скриптов на агентах вылетают всякие странные ошибки.
И бывает сложно понять, причина в скрипте, окружении скрипта, параметрах скрипта или неверной библиотеке. Разбор полетов сложен и хочется максимально его упростить.
Это борьба за качество разработки, без которого никуда.

Правильный деплой/установка поможет частично решить эту проблему, но не всегда возможен правильный деплой :) 
Поэтому мне, как пользователю/разработчику скрипта, очень бы хотелось видеть, что мой скрипт юзает правильную версию библиотек. 
Пусть скрипт падает по понятной причине, а не по странной :)

Поэтому и родилась эта issue

ЗЫ могу даже в формате Геркина сформулировать эту хотелку :)

**Comment by nixel2007** [comment]
offtopic
@artbear твою проблему частично может решить подход, описанный в #32. Если пофиксят ту issue :)

**Comment by artbear** [comment]
@nixel2007 Частично решит, но мне не хочется юзать "локальные" версии библиотек, это тоже зло ада версий в немного другой "упаковке" :)

**Comment by nixel2007** [comment]
opm в данном данном случае будет идеальным решением на мой взгляд. Если будет возможность как, например,  в npm положить файлик со всеми зависимостями, которые ставятся одной командой update.

**Comment by EvilBeaver** [comment]
Поддержу @nixel2007 

Правильный вариант деплоя:

```
opm install -f my-build-tools.ospx
```

и получаешь апдейт всех зависимостей. Конкретные ключи и тех.детали сейчас опускаем, но работать должно как-то так. Копирование файликов должно умереть. Ну или не иметь отношения к управлению версиями.

**Comment by artbear** [comment]
> Правильный вариант деплоя: 'opm install -f my-build-tools.ospx'

и что нужно сделать, чтобы это заработало?
задокументировать? :)

**Comment by EvilBeaver** [comment]
Ах, если бы! Это надо написать :) В принципе, там есть операция update но контроля версий нет.

**Comment by artbear** [comment]
@EvilBeaver Приведи сценарий поведения по update и install для контроля версий

**Comment by EvilBeaver** [comment]
@artbear я описал в каменте выше:

> В идеале - при установке программы, которая требует lib-1.5 opm должен сам обновлять текущую lib-1.1 до нужной версии.

**Comment by nixel2007** [comment]
В продолжение темы.

Помимо определенного хорошей идеи с пакетами и пакетным менеджером необходимо продумать алгоритм версионирования для модулей, поставляемых в исходных кодах, то бишь в os.

Например, пакета может не быть вообще. Или мы работаем с дев-версией какой-то библиотеки, скачанной с гитхаба в сорцах.

**Comment by EvilBeaver** [comment]
> Или мы работаем с дев-версией какой-то библиотеки, скачанной с гитхаба в сорцах

Вот это я против. Скачал дев - сам следи и сам обновляй. Автор должен так или иначе обеспечивать работу релизного пакета. В идеале - собранного через opm и опубликованого в хабе. Все, что из исходников, да еще и из dev-а - это полуфабрикат, у которого версии быть не может.

Если кто знает веббера, готового написать простенький бэкенд (да и фронтенд) для hub.oscript.io (разумеется, ради мира во всем мире и никак не за злато) - сообщайте!

Версионирование нужно. Но в каком виде - вопрос. Бывает жесткое, бывает мягкое. Версионирование, когда "пакета нет вообще" я тоже себе слабо представляю. А версия **"чего"** тогда должна контролироваться?

**Comment by ghost** [comment]
@EvilBeaver я правильно понимаю - что нужно что-то подобное https://gopm.io/ ?

Тогда вынужден вам сказать, что в GoLang решили проблему зависимостей библиотек и версий в стиле Спартака "Спартак решил проблему защиты, нет защиты не проблемы"

Сам удивлен - не скажу что это правильно, но как вариант прикольно

зависимость пакета определяется таким вот файлом

``` YAML
[target]
github.com/alustin/main-go

[deps]
github.com/bradfitz/gomemcache = commit:72a68649ba
github.com/codegangsta/cli = commit:b5232bb
github.com/go-macaron/binding = commit:2502aaf
github.com/go-macaron/cache = commit:5617353
github.com/go-macaron/captcha = commit:8aa5919
github.com/go-macaron/csrf = commit:715bca0
github.com/go-macaron/gzip = commit:4938e9b
github.com/go-macaron/i18n = commit:d2d3329
github.com/go-macaron/inject = commit:c5ab7bf

[res]
include = public
```

то есть для пакета определяется зависимость как:
- адрес git хранилища
- коммит хранилища

и всё

**Comment by ghost** [comment]
ну и соответственно можно указать либо тэг git репозитория либо branch

```
github.com/bradfitz/gomemcache = branch:master
github.com/bradfitz/gomemcache = tag:1.0
```

**Comment by ghost** [comment]
Чтобы подытожить - архитектура следующая в GoLang
- имя пакета определяет полный URI где находится git репозиторий без http
- внутри каждого пакета могут находиться модуля который дополняют URI - таким образом можно установить зависимость от отдельного модуля, а не от целого пакета

и теперь главное
- поле версия служит для коммуникации с пользователем - то есть тупо для показа

`вы используете версию 1.0.23.34`

для управления зависимостями используется указание на SHA адрес commit'а, так как все git сервера сейчас используют единообразные URI
то допустима зависимость формата https://github.com/EvilBeaver/oscript-library/commit/a0aa7b2ff998e770ae4ebedcf561876a00c16f09

в книге Эффективный Go - есть отсылка на эту тему, что дескать - развивающиеся библиотеки фактически улучшают свою стабильность каждый день и нет времени играться с версиями, давайте играться с git ссылками - это типа удобней.

а степень доверия к библиотеке определяется не её качеством игры в Версионность, а оценке качества по другой метрике http://goreportcard.com/

например http://goreportcard.com/report/nlopes/slack - интегратору slack доверять не особо можно, так как он имеет качестве уровня B

всякие Bundle и Gem, а также Maven меня несколько подзадолбали и в подходе GoLang меня многое радует

**Comment by nixel2007** [comment]
Кстати, теперь, когда @EvilBeaver реализовал поиск библиотек по имени по конфиг файлу в папке скрипта это стало сделать ещё проще. 

В скрипте написано, что нужен logos. 
В конфиге написано, что библиотеки надо искать в, допустим, ./oscript_modules
В другом (или том же) конфиге, написано, что нужна logos версии какой-нибудь. 

opm install установит нам logos в папку oscript_modules, а интерпретатор oscript сам подключит нужную версию библиотеки. 

И...  Вроде все. 
Идейных противоречий не видите?

**Comment by EvilBeaver** [comment]
> opm install установит нам logos в папку oscript_modules

opm сам ничего не установит при запуске какого-либо скрипта. Идея зависимости от коммита - интересная, но ее надо прорабатывать, опять же, в плане идеи проекта. А идея такая, что 1С-ники не знают что такое git, а если знают, то про sha-commit не совсем в курсе. Я вот, например, не знаю, как универсально сослаться на конкретный коммит, так, чтобы любой консольный git знал - какой файл надо получить.

Посему, хотелось бы указание зависимостей в виде geek-style адресов git убрать для продвинутых пользователей.

Проблема у @IslamA проявилась из-за того, что в precommit никаким образом не указывались зависимости - какие версии/коммиты/чтоугодно нужны, чтобы все работало.

И уже второй вопрос - как все эти зависимости должны разрешаться и доставляться на клиентскую машину.

**Comment by nixel2007** [comment]
> opm сам ничего не установит при запуске какого-либо скрипта.

это понятное дело. но этот шаг можно включить в README по установке/использованию скрипта.
Скачали, opm install, а потом уже запустили.

**Comment by nixel2007** [comment]
Шаг проверки используемых библиотек можно зашить в сам интерпретатор.
- При запуске файла os по конфиг-файлу с зависимостями определять необходимые версии подключаемых библиотек
- При использовании директивы #Использовать на основании package.def подключаемой библиотеки определяется ее версия
- При несовместимости версий вываливается исключение

@EvilBeaver реальный вариант (в плане доработок oscript)?

**Comment by nixel2007** [comment]
> Проблема у @IslamA проявилась из-за того, что в precommit никаким образом не указывались зависимости - какие версии/коммиты/чтоугодно нужны, чтобы все работало.

Понятное дело :) Просто хочется выработать подход, который потом уже можно внедрять в любую библиотеку/скрипт

**Comment by EvilBeaver** [comment]
Я не хочу инфраструктуру библиотек сильно зашивать в интерпретатор. Но определять зависимости можно. Как команда, скажем, `get-depends`, которая на выходе будет возвращать описание зависимостей запускаемого файла. А этот результат команды потом может обрабатывать **opm** и так или иначе устанавливать то, что нужно.

**Comment by nixel2007** [comment]
> Как команда, скажем, get-depends, которая на выходе будет возвращать описание зависимостей запускаемого файла.

Не соглашусь.
В скрипте написано - `#Использовать asserts`
А в самой `asserts` либо:
- написано `#использовать logos`
- в package.def есть зависимость от `logos`

То есть... Пока мы через _opm_ не скачаем/установим библиотеку (причем нужной версии), мы все равно не сможем построить полное дерево зависимостей.

**UPD**: Не соглашусь именно в плане того, что определение зависимостей надо вложить в интерпретатор. Это все же задача пакетного менеджера.
А вот отсутствие удовлетворенной зависимости уже можно обрабатывать интерпретатором (выдавая человеко-понятные исключения).
Имхо.

**Comment by EvilBeaver** [comment]
@nixel2007 Интерпретатор в любом случае строит дерево зависимостей. Вернее, не дерево, а список каталогов библиотек. По имени или нет - не важно, он все равно все сводит к путям.

на выходе может получиться таблица вида:

| Имя | Разрешается в |
| --- | --- |
| logos | C:\lib\logos |
| somelib | C:\customlib\somelib |
| "local" | C:\script-dir\local |

Если какая-то либа вообще не разрешилась ни в одном из мест поиска - компиляция невозможна. Будет ошибка.

Если все разрешились - opm может просмотреть эту таблицу, сверяясь с требуемыми версиями, объявленными в packagedef. Если версия в таблице разрешенных зависимостей не совпадает с требуемой версией - предпринимаются меры по обеспечению версии.

**Comment by nixel2007** [comment]
@EvilBeaver и тут я понял, что ты имел ввиду, и что теперь я противоречу сам себе :)

Попробую еще раз сформулировать мысль без конфликтов:

``` gherkin
Чтобы минимизировать последствия от отсутствия или несовместимости библиотек
Как неопытный пользователь oscript
Я хочу чтобы интерпретатор oscript при конфликте версий выдавал мне понятную ошибку

    Сценарий: Выдача понятных исключений
        Пусть есть файл скрипта test_script.os
            И есть описание скрипта
            И в описании скрипта есть зависимость от logos версии 2.0+
            И logos 2.0 или старше не установлена
        Когда я выполняю команду oscript test_script.os
        Тогда интерпретатор oscript получает список библиотек
            И интерпретатор выдает исключение о неудовлетворенной зависимости
```

То, что ты не хочешь зашивать в интерпретатор инфраструктуру библиотек, я понимаю и согласен, что это потенциальная проблема.
Но при этом "как неопытный пользователь oscript" (да и как просто пользователь обновившегося скрипта с обновившимися зависимостями) я не хочу перед каждым запуском скрипта тыкать opm install. Хочу запустить скрипт, и вот если уж что-то упало - тогда уже разбираться.

**Comment by EvilBeaver** [comment]
> я не хочу перед каждым запуском скрипта тыкать opm install. Хочу запустить скрипт, и вот если уж что-то упало - тогда уже разбираться.

Открою секрет - как правило, так и будет происходить в 99.999% случаев :smile: 

Если после обновления вдруг неожиданно выяснилось наличие breaking changes, то только тогда мы и дергаем opm. В большинстве случаев обновления все же безопасны.

**Comment by nixel2007** [comment]
может мы видим разные сценарии использования. мне на данный момент больше импонирует вариант, который используется в node.js (да-да, опять я про него). 
0) ты _можешь_ установить любые пакеты (но только одной версии) в глобальный каталог библиотек
1) в каталоге проекта у тебя есть файл, в котором указаны зависимости (package.json)
2) когда ты делаешь `npm install` он их складывает в локальный каталог node_modules (создает, если его нет)
3) когда ты используешь в коде `require('logos');`, то он сначала ищет этот модуль в локальном каталоге node_modules, потом уже пытается найти его в глобальном каталоге.

похожее поведение можно реализовать: 
- либо задефайнить, например, `oscript_modules` как один из стандартных каталог поиска библиотек
- либо положив рядом со скриптом файл, где бы этот каталог подключался (через твою доработку в 1.0.12)

было бы здорово, если бы оба варианта работали одновременно. Но это требует вмешательства в интерпретатор (в интерпретаторе node.js это сделали).
Плюс доработка opm для локальной установки библиотек в локальный заданный каталог.

**Comment by EvilBeaver** [comment]
Сценарий нормальный. Более того, он даже сейчас будет работать, вмешательство в интерпретатор не требуется. opm может прописать рядом со скриптом файл конфига, нацелить его на папку modules и готово.

Я только один момент не понял: если npm складывает все зависимости в локальный каталог, то в глобальный он уже не полезет. Ведь все зависимости уже сидят локально, нет?

**Comment by nixel2007** [comment]
> Я только один момент не понял: если npm складывает все зависимости в локальный каталог, то в глобальный он уже не полезет. Ведь все зависимости уже сидят локально, нет?

Если мне память не изменяет, то ты можешь все зависимости тоже глобально установить.
Или вообще руками часть глобально (`npm install -g package_name1`), часть локально (`npm instal package_name2`).

> Более того, он даже сейчас будет работать, вмешательство в интерпретатор не требуется.

Согласен. Но "красивых исключений" на уровне интерпретатора opm не сможет предоставить :)  
Не, если такой функционал только у меня в голове как фича, и нужен только мне, то ради бога.
Просто пытаюсь себя избавить от потенциальных проблем.

**Comment by EvilBeaver** [comment]
@nixel2007 функционал нужен. А что ты понимаешь под "красивыми исключениями"? Текущее "библиотека не найдена libname" в какую сторону можно украсить?

**Comment by nixel2007** [comment]
@EvilBeaver не только, что библиотека не найдена, но и что версия не та.

**Comment by nixel2007** [comment]
Ну и как пожелание по указанию зависимостей версий - поддерживать хоть сколько-нибудь нечеткий синтаксис:
https://github.com/npm/node-semver#versions

Хотя бы на уровне `>=1.2.3`

**Comment by EvilBeaver** [comment]
Вот я все это хочу оставить на уровне скриптов и opm. Например, потому, что это будет проще доработать тем, кто не знает C#. Сейчас нечеткий синтаксис в opm как бы есть, но в зачаточном виде и, можно сказать, что его совсем нет.

**Comment by nixel2007** [comment]
@EvilBeaver как бы поиграться с `opm` в плане разработки на локальной машине? чтобы позапрашивать (с хаба? с локального каталога?) разные версии хотя бы двух пакетов?

**Comment by artbear** [comment]
> Если кто знает веббера, готового написать простенький бэкенд (да и фронтенд) для hub.oscript.io (разумеется, ради мира во всем мире и никак не за злато) - сообщайте!

Среди нас есть такой человек @kuntashov 
@EvilBeaver пообщайся с Сашей, он в бэкэндах и фронтэндах веб-строительства ИМХО больше нас всех понимает.

**Comment by EvilBeaver** [comment]
@nixel2007 взять opm, впилить туда функционал "альтернативного локального хаба", потом играться.

@artbear Саша занятой и дергать его неудобно.

**Comment by kuntashov** [comment]
> Среди нас есть такой человек @kuntashov 
> @EvilBeaver пообщайся с Сашей, он в бэкэндах и фронтэндах веб-строительства ИМХО больше нас всех понимает.

Спасибо за рекомендацию :)
Надо хотя бы общие требования к функционалу/сценарии сформулировать.
Я по факту являюсь пользователем всяких пакетных менеджеров (того же npm или phpшного composer), но честно говоря о всей внутренней механике не приходилось задумываться (как устроено). Но не против поразбираться на досуге.

**Comment by artbear** [comment]
> @artbear Саша занятой и дергать его неудобно.

Ну он же за мир во всем мире :) поэтому подходит под твою выборку :)

**Comment by EvilBeaver** [comment]
@kuntashov нужен именно человек, который сайт хаба пакетов сделает. Хранение, авторизация, добавление репо, где разрабатывается пакет, добавление самого пакета. Ну и плюшки всякие в виде красивой странички с описаниями пакетов

**Comment by kuntashov** [comment]
> @artbear Саша занятой и дергать его неудобно.

Ты меня списал со счетов из-за того, что я с HTTP не успел помочь? :) 
Я действительно торможу сейчас по отношению к side-проектам, но вроде в мире open source к этому терпимо относятся, пусть потихоньку, но главное, чтобы контрибутилось :)

Если у тебя конечно же какие-то жесткие планы с конкретными сроками, то да, я не лучший кандидат, но такая ситуация плохо вяжется с

> разумеется, ради мира во всем мире и никак не за злато

:)

**Comment by nixel2007** [comment]
> Хранение, авторизация, добавление репо, где разрабатывается пакет, добавление самого пакета.

и API, чтобы его забрать :D а то все остальное будет уже не так важно))

**Comment by kuntashov** [comment]
@nixel2007 а расскажи кратко, как на packagecontrol.io это организовано с точки зрения пользователя.
Ты пакет туда заливаешь как архив или просто ссылку на гитхаб даешь, а он сам все собирает?

**Comment by EvilBeaver** [comment]
@kuntashov я не списал, наоборот, понимаю, как сложно выкроить время на опен-сорс. Никаких "списываний со счетов" с моей стороны, ты это брось :smile:

**Comment by kuntashov** [comment]
@EvilBeaver я шучу ) твое внимание и понимание того, что я занят (как в общем-то, и все участники), ценю, спасибо )

**Comment by nixel2007** [comment]
@kuntashov packagecontrol.io вообще немного странный.
Надо добавить в специальный json в репо самого packagecontrol описание ссылку на твой пакет и способ версионирования (по факту сейчас не-deprecated метод только один - git tag master-ветки) и сделать PR в его репо.

После принятия PR тебе остается сделать git tag по правилам semver и запушить на свой гитхаб. packagecontrol раз в N минут (на вскидку раз в 30) чекает все репозитории, объявленные в его json и обновляет статистику у себя во внутрях. После обновления статистики ты уже можешь забирать пакет к себе в редактор.

**Comment by nixel2007** [comment]
@kuntashov мне больше apm в этом плане нравится. ему не требуется никаких указаний в json где-то слева.
ты просто делаешь apm publish version (оно так же работает на основе тэгов гита), он отправляет данные на сам apm-сайт и сразу все работает.

**Comment by kuntashov** [comment]
@nixel2007 спасибо, очень гиковский интерфейс :)
Про git tag я как раз и думал как про основной способ идентификации версий пакетов, зарегистрированных на hub.oscript.io репозиториев скриптов-"библиотек".

**Comment by nixel2007** [comment]
@kuntashov в пакетном менеджере VS Code тоже используется git tag, если я правильно понимаю его работу.
Так что можно считать это стандартом (по крайней мере для редакторов) :)

**Comment by dmpas** [comment]
@EvilBeaver Версии вроде есть в библиотеках. По сути задачи - её можно закрывать.

**Comment by EvilBeaver** [comment]
Согласен, закрываю, т.к. идет параллельный процесс развития opm
