### ISSUE TITLE
tab vs space 

### ISSUE THREAD

**Issue by pumbaEO** [EvilBeaver/oscript-library#35]

**Comment by artbear** [comment]
@pumbaEO @EvilBeaver  Вы за tab или пробелы?

**Comment by pumbaEO** [comment]
за пробелы.

**Comment by dmpas** [comment]
Наследие 1С как-бы насаждает нам табы.

**Comment by EvilBeaver** [comment]
Я как-то хабре видел концепцию - отступы табами, выравнивание пробелами. С тех пор использую.

```
Если Истина Тогда
    Б = 1; // это отступ, здесь табы
    В = 2;
КонецЕсли

ДлиннаяПеременная = 5;
ЗдесьПокороче     = 3; // это выравнивание, здесь пробелы
```

А в целом, холивар старый, меня давно не парит. Использую то, что стоит в редакторе по умолчанию и готов принять любой символ, если он всех устраивает.

**Comment by pumbaEO** [comment]
Табы в браузере при diff плохо выглядят.

16 ноября 2015 г., 17:03 пользователь Andrei Ovsiankin <
notifications@github.com> написал:

> Я как-то хабре видел концепцию - отступы табами, выравнивание пробелами. С
> тех пор использую.
> 
> Если Истина Тогда
>     Б = 1; // это отступ, здесь табы
>     В = 2;
> КонецЕсли
> 
> ДлиннаяПеременная = 5;
> ЗдесьПокороче           = 3; // это выравнивание, здесь пробелы
> 
> А в целом, холивар старый, меня давно не парит. Использую то, что стоит в
> редакторе по умолчанию и готов принять любой символ, если он всех
> устраивает.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EvilBeaver/oscript-library/issues/35#issuecomment-157038394
> .

## 

З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by artbear** [comment]
Мне также все равно, Ctrl+Del или Ctrl+Backspace удаляет все, хоть таб, хоть пробел, хоть слово

**Comment by nixel2007** [comment]
Плюсы табов - возможность настроить любую ширину отступа в редакторе, хоть 2 хоть 4 символа.

**Comment by artbear** [comment]
> Плюсы табов - возможность настроить любую ширину отступа в редакторе, хоть 2 хоть 4 символа. 

И эта же возможность является их главным злом, т.к. форматирование у всех выглядит по-разному :(

**Comment by EvilBeaver** [comment]
@nixel2007 а оно надо? Я знаю про эту опцию, сколько имею компьютер. И ни разу не настраивал, за исключением случаев, когда оно было по умолчанию выставлено в "8". На 15-дюймовом мониторе это было жестоко.

**Comment by nixel2007** [comment]
Зависит от принятых стандартов форматирования. Стандартное (перевод строки + один таб) будет выглядеть у всех одинаково. Догонять же отступы под, например, скобки при вызове функций с большим количество - не самое удачное с точки зрения форматирования решение, имхо

**Comment by pumbaEO** [comment]
У github принято tab = 8 символов, https://github.com/EvilBeaver/oscript-library/pull/33/files#diff-b4a7e51294a8e34136c110fbae01bef1L415

**Comment by EvilBeaver** [comment]
Ну, короче, я как все, мне не принципиально. Каких-то аргументов за или против табов не имею.

**Comment by artbear** [comment]
Предлагаю голосовать
я и @EvilBeaver воздерживаемся.
Ждем остальных.

**Comment by JohnyDeath** [comment]
Не принципиально, но если уж голосовать, то проголосую за tab, т.к. все мы как-то связаны с 1С, где приняты tab-ы

**Comment by awa15** [comment]
За tab!

**Comment by nixel2007** [comment]
Если имею право голоса - за таб.

**Comment by ghost** [comment]
Я каюсь - я продолжаю переход на пробелы. От табов как-то отказываюсь, но руки иногда косячят. Поэтому я не то чтобы воздержусь - я буду стараться делать пробелами: мне тут давеча объяснили почему это хорошо.

**Comment by nixel2007** [comment]
@allustin так поделись с нами :)

**Comment by pumbaEO** [comment]
Space
16 нояб. 2015 г. 21:42 пользователь "Nikita Gryzlov" <
notifications@github.com> написал:

**Comment by dmpas** [comment]
табы

**Comment by ghost** [comment]
@nixel2007 там долго ;-). мне часа 3 объясняли.

если коротко - то tab это это "операция", а пробел это "символ языка". 
то есть в исходниках необходимо использовать символы, а при операциях использовать горячие клавиши.

например в Word "табуляция" это правильно, а в Markdown нет. 

Вообщем как сказал @EvilBeaver - это старый холивар.

**Comment by EvilBeaver** [comment]
@nixel2007 @allustin ну короче, я отписался уже выше - я использую табы, но за них не держусь. Раз пошла такая пьянка, то я тоже за табы, ибо 1C-way.

**Comment by artbear** [comment]
Итого на 17.11 12:13
5 за таб
2 за пробелы
1 воздержался

Кто еще голосует?
@wizi4d ?

**Comment by EvilBeaver** [comment]
А у меня вопрос зачем это все? Ну допустим таб победил. И?

-----Исходное сообщение-----
От: "Artur Ayukhanov" notifications@github.com
Отправлено: ‎17.‎11.‎2015 12:14
Кому: "EvilBeaver/oscript-library" oscript-library@noreply.github.com
Копия: "Andrei Ovsiankin" ovsiankin.aa@gmail.com
Тема: Re: [oscript-library] tab vs space  (#35)

Итого на 17.11 12:13
5 за таб
2 за пробелы
1 воздержался
Кто еще голосует?
@wizi4d ?

**Comment by dmpas** [comment]
@EvilBeaver будешь гневно отметать все запуллы с формулировкой "у вас отступы пробелами!"

**Comment by nixel2007** [comment]
@evilbeaver можно устроить народные гуляния, с фейерверками и маскарадом. 
А если серьёзно, то радикальный вариант - переформатировать все существующие os'ы и впредь придерживаться единого стиля

**Comment by dmpas** [comment]
кстати, вот тут нагрепал на злобу дня:
https://github.com/EvilBeaver/oscript-library/blob/develop/src/v8runner/src/v8runner.os#L199

**Comment by EvilBeaver** [comment]
@dmpas ОУЖОС! пробелы в моем в8раннере!! :scream_cat: 
А по поводу отметания запуллов, тут кроме присутствующих никто их и не делает, хоть с пробелами, хоть нет :(

**Comment by nixel2007** [comment]
@evilbeaver единые стандарты разработки могут помочь даже одному разработчику, не говоря уже о 5+ :)
