### ISSUE TITLE
Gitsync неверно работает c 8.3.7

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#39]
В 8.3.7 по умолчанию используется иерархический формат при выгрузке.

Нужно доработать код для использования старого формата + влить пулл-реквест #38 для использования нового формата.

Исправлю сам.

**Comment by artbear** [comment]
C 8.2 я написал неверно, мы сразу ориентировались на 8.3
Осталась проблема работы с 8.3.7

**Comment by EvilBeaver** [comment]
@artbear там по пулреквесту #38 @pumbaEO что-то еще вроде хотел доделать перед слиянием, не?

**Comment by artbear** [comment]
@EvilBeaver наверное, ты уже увидел, что я ему отписался на странице пулл-реквеста

**Comment by artbear** [comment]
Проблема в том, что у меня за время болезни неделю выгружались пустые правки в Гит :) (3 пустых файла)
Для меня исправление нужно очень срочно.

**Comment by artbear** [comment]
@pumbaEO Обрати внимание на мое исправление, предлагаю слить #38 и эту правку.
