### ISSUE TITLE
Пакетный менеджер

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/oscript-library#4]
Нужен функционал:
- Версионирования пакетов
- Управления зависимостями
- Подгрузки пакетов из облака hub.oscript.io
- Хелпер создания новых пакетов

**Comment by ghost** [comment]
Не будет делаться ?

**Comment by EvilBeaver** [comment]
Уже сделано. В виде прототипа, конечно, но рабочего. Собирает пакеты, Устанавливает, Качает с облака. Нужна помощь в тестировании, документировании, рецензия и вообще, всяческий feedback. http://hub.oscript.io

-----Исходное сообщение-----
От: "Alexey Lustin" notifications@github.com
Отправлено: ‎25.‎09.‎2015 19:08
Кому: "EvilBeaver/oscript-library" oscript-library@noreply.github.com
Копия: "Andrei Ovsiankin" ovsiankin.aa@gmail.com
Тема: Re: [oscript-library] Пакетный менеджер (#4)

Не будет делаться ?

**Comment by dmpas** [comment]
HTTPS будет?

**Comment by EvilBeaver** [comment]
@dmpas, а зачем? Что шифровать - открытые исходники?

**Comment by dmpas** [comment]
HTTPS - это далеко не только шифрование траффика. Это ещё уверенность, что hub.oscript.io - именно тот сайт, который мне нужен, а не какой-то иной.

**Comment by EvilBeaver** [comment]
ИМНИП, для проверки подлинности сайта его сертификат должен быть выпущен доверенным центром за бабло, не?

**Comment by dmpas** [comment]
не обязательно. достаточно, чтобы я у себя хранил сертификат и при соединении сравнивал его. это называется "самоподписанные сертификаты". к тому же, есть центры сертификации, подписывающие сертификат бесплатно.

**Comment by EvilBeaver** [comment]
Про бесплатных не слышал, можно поискать. А в случае самоподписанного придется каким-то безопасным образом распространять этот ключ среди заинтересованных. Хотя, это повод собраться за чашкой кофе;)

**Comment by ghost** [comment]
Самоподписанный не надо. Лучше выпустить бесплатный на домен hub.oscript.io
Иначе небезопасно.

На Хабре есть простая инструкция как сделать персональный сертификат на один домен. Сложности возникают когда нужно выпустить на организацию и с wildcard.  Такой нам обошелся в 20 килорублей в год.

**Comment by dmpas** [comment]
20 килорублей в год - это много.

**Comment by ghost** [comment]
Это если на юрлицо и на несколько доменов . Персональный бесплатно.

**Comment by artbear** [comment]
@EvilBeaver Как пользоваться-то?
Только что скачал инстальник от ночной версии, установил все.
Запускаю opm и получаю ошибку

```
C:\Program Files (x86)\OneScript>opm install gitsync
"opm" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
```

И это логично, т.к. никакого исполняемого файла opm не появилось.

**Comment by artbear** [comment]
1. Пытаюсь запустить вручную, через oscript. Получаю баг

```
C:\Program Files (x86)\OneScript\lib\opm\src>oscript opm.os install opm
{Модуль C:\Program Files (x86)\OneScript\lib\opm\src\opm.os 
/ Ошибка в строке: 13 / Неизвестная директива: !(!/usr/bin/oscript)}
```

Баг при работе в Windows ?

2 Комментирую первую строку, запускаю дальше
Получаю баг, как и у Валеры Агеева (на битбакете)

```
C:\Program Files (x86)\OneScript\lib\opm\src>oscript opm.os install opm
ОТЛАДКА - {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\Классы\КэшУстановленныхПакетов.os / Ошибка в строке: 14 
/ Внешнее исключение: Не удалось найти часть пути "C:\Program Files (x86)
\OneScript\lib\opm\lib".}
Внешнее исключение: Не удалось найти часть пути "C:\Program Files (x86)\OneScript\lib\opm\lib".
```

Еще баг?

**Comment by EvilBeaver** [comment]
> Только что скачал инстальник от ночной версии, установил все. Запускаю opm и получаю ошибку

@artbear это дубликат #22

**Comment by awa15** [comment]
То, что opm.bat отсутствует в инсталяхе - это одно. Имхо, ошибка в том, что путь библиотеки определяется относительно текущего каталога, хотя в параметрах он прописан относительно каталога bin (т.е. относительно КаталогПрограммы()). Когда opm.bat лежит в каталоге bin - ошибок нет, эти пути совпадают. Но никто не запрещает же запускать скрипт как я и Артур.

**Comment by EvilBeaver** [comment]
@awa15 можешь пояснить, пожалуйста? Уже вторая половина дня, я понимаю только на пальцах ))

**Comment by awa15** [comment]
@EvilBeaver когда я запускаю opm.os прямо в каталоге "C:\Program Files (x86)\OneScript\lib\opm\src" (как @artbear описал чуть выше), то текущий каталог, соответственно, "C:\Program Files (x86)\OneScript\lib\opm\src".
Системная настройка lib.system определена как "../lib".
В файле КэшУстановленныхПакетов.os выполняется такой код:
    КаталогБиблиотек = ПолучитьЗначениеСистемнойНастройки("lib.system");
    НайденныеФайлы = НайтиФайлы(КаталогБиблиотек, ПолучитьМаскуВсеФайлы());
Таким образом и получается, что файлы ищутся в каталоге "C:\Program Files (x86)\OneScript\lib\opm\lib", которого не существует.

**Comment by artbear** [comment]
@awa15 +1

**Comment by EvilBeaver** [comment]
Ну тогда получается это баг. Кто первый зафиксит, тот молодец! :trollface:

**Comment by artbear** [comment]
> Ну тогда получается это баг. Кто первый зафиксит, тот молодец! :trollface:

Сегодня я молодец :)

**Comment by EvilBeaver** [comment]
А где тесты? :trollface: 
А если серьезно, то @artbear, @awa15  - спасибо за помощь!
