### ISSUE TITLE
ВременныеФайлы: доработать получение имен и путей для новых файлов (добавить СлучайноеИмяФайла)

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#41]
Сейчас у нас используется метод `НовоеИмяФайла`
ИМХО имя этого метода не отвечает своему функционалу, т.к. возвращает не имя файла, а полный путь.
Возникает путаница с терминологией: у нас есть путь, полное имя, имя файла и есть метод, который должен возвращать имя, а возвращать полный путь/полное имя.

Предлагаю разделить функционал этого метода на два метода:
- `НовоеИмяФайла` - получает именно имя нового файла, без пути к файлу
- `НовоеПолноеИмяФайла` - получает именно полное имя нового файла, т.е. полный путь с именем файла

Новые функции удобны, когда нужно разделять работу с новыми временными файлами в нужном каталоге или работу со временными файлами из временного каталога системы.

**Comment by nixel2007** [comment]
Что с обратной совместимостью?  
В моих скриптах, например, используется полный путь, т.к. он нужен принимающим программам/скриптам.

Варианта два:
- объявить об отсутствии полной обратной совместимости в новой версии библиотеки
- поступить, как, например, поступают в БСП - добавить два новых метода, условно `ПолучитьНовоеИмяФайла` и `ПолучитьНовоеПолноеИмяФайла`, объявив старую функцию как deprecated (с выводом сообщения на уровне лога `Отладка`, плюс отразить в документации), а в последствии, через пару мажорных релизов удалить.

**Comment by EvilBeaver** [comment]
@artbear с терминологией здесь всегда проблемы. Даже у буржуев в документации и в API часто перемешаны name. fullname, path, full path, name-without-extension, base name и т.д. и т.п.

Я бы оставил as-is, а если тебе нужно только имя (кстати, зачем?) можно сделать отдельный метод. Только назвать получше.

**Comment by artbear** [comment]
@EvilBeaver Я же описал:

> нужно разделять работу с новыми временными файлами в нужном каталоге или работу со временными файлами из временного каталога системы.

Например, мне нужно создать временный файл именно в указанном каталоге, а не во временном каталоге системе.
Сейчас приходится получать полный путь из сабжа, далее создавать файл, и объединять путь нужного каталога и имя из файла.
лишний и некрасивый код, который дублируется в нескольких местах

**Comment by EvilBeaver** [comment]
> Например, мне нужно создать временный файл именно в указанном каталоге, а не во временном каталоге системе.

@artbear ты опять говоришь о решении некой проблемы, а не о самой проблеме. Я попробую перефразировать: для чего нужны файлы с абракадабровыми именами в НЕвременном каталоге? Они же не нужны там сами по себе, ты решаешь некую задачу таким способом. Вот я про задачу и спрашиваю...

Я почему докапываюсь: API должен удовлетворять неким сценариям. А мы, как авторы, должны эти сценарии себе представлять. Я понимаю зачем нужны временные файлы. Я не совсем понимаю, зачем они нужны без каталога.

Как вариант могу предложить метод "СлучайноеИмяФайла()" - оно в .net как раз там низом и используется. Но если меня спросят: "Для чего нужен такой метод в API", я ответить не смогу. Поможешь?

**Comment by EvilBeaver** [comment]
@artbear подниму вопрос

**Comment by artbear** [comment]
Я говорил именно о проблеме.

Мне для конвертации тестов xUnitFor1C из 3.Х в 4.Х нужно было создавать набор временных каталогов и файлов внутри них.
создать исходный временный каталог в системном временном каталоге я могу (через НовоеИмяФайла получаю полный путь)
далее **в этом новом временном каталоге** мне нужно сохранить файлы из макета, выдав файлу временное имя, и создать дополнительные доп.каталоги с временным именем, в которых также нужно сохранить файлы из макета, выдав файлу временное имя.

Как я и писал выше, сейчас это сделать сложно

> Например, мне нужно создать временный файл именно в указанном каталоге, а не во временном каталоге системе.
> .
> Сейчас приходится получать полный путь из сабжа, далее создавать файл, и объединять путь нужного каталога и имя из файла.
> лишний и некрасивый код, который дублируется в нескольких местах

@EvilBeaver Достаточно этого сценария? Или все-таки непонятна проблема?

**Comment by EvilBeaver** [comment]
я ничего не понял, но наверное, это нужный функционал. Только предлагаю такой метод назвать "СлучайноеИмяФайла"

**Comment by artbear** [comment]
Да, `СлучайноеИмяФайла` нормально

**Comment by artbear** [comment]
Сделаю?

**Comment by EvilBeaver** [comment]
@artbear сделай

**Comment by demidych** [comment]
А зачем конкретизировать что это случайное имя именно файла? Ведь через это имя можно и каталоги создавать и файлы, а по имени метода как будто ограничение накладывается , что можно создавать только файлы.
Мне кажется правильнее "СлучайноеИмя". И если гарантируется его уникальность, то может тогда даже лучше "УникальноеИмя".

**Comment by artbear** [comment]
Ага, вариант `УникальноеИмя` мне больше нравится.
Для схожести с текущим АПИ `НовоеИмяФайла` предлагаю юзать вариант `УникальноеИмяФайла`

**Comment by artbear** [comment]
@EvilBeaver Или все-таки `УникальноеИмя` ?

**Comment by EvilBeaver** [comment]
Уникальность там не обеспечивается, ибо уникальность можно сделать, только если "застолбить" имя созданием файла с таким именем. Поэтому, в C# метод называется GetRandomFileName. Оно случайное и почти уникальное, но тем не менее, не гарантирует.

**Comment by awa15** [comment]
Имхо, лучше сделать отдельно методы `УникальноеИмяФайла(Каталог, Расширение = "")` и `СлучайноеИмя()`.

**Comment by demidych** [comment]
Еще по поводу имен.
Когда есть класс ВременныйФайлы, то в именах его методов лучше не использовать "Файл", "Файлы" и т.д., т.к. получается только дублирование и лишняя писанина.
Например были методы: СоздатьНовоеВременноеИмяФайла(), СоздатьВременныйФайл(), СоздатьВременныйКаталог(). Выделили их в класс ВременныеФайлы() и получили: СоздатьНовоеИмя(), Создать(), СоздатьКаталог().

И еще по поводу библиотеки в целом - хорошо бы у экспортных методов писать комментарии, например в "стандартном" стиле 1С:
// Описание функции
// Параметры:
//   Параметр - Тип - описание параметра.
// Возвращаемое значение:
//   Тип - описание возвращаемого значения.

**Comment by artbear** [comment]
Я согласен с @demidych, что от тавтологии нужно избавляться.
Предлагаю 
1. Добавить публичные методы-дубли
- Например, для `НовоеИмяФайла` создаем `НовоеИмя`
- В начале кода `НовоеИмяФайла` пишем `Сообщить("Устаревший метод НовоеИмяФайла, будет отключен в следующем релизе. Используйте НовоеИмя");`
1. Создать новый метод `СлучайноеИмя`

@EvilBeaver Что скажешь? могу сегодня/завтра сделать

**Comment by nixel2007** [comment]
@artbear а вопрос с терминологией отложили? Что "НовоеИмяФайла" возвращает полное имя, а не само имя файла?

**Comment by artbear** [comment]
@nixel2007 Спасибо за напоминание, подзабыл :)

Напоминаю :

Сейчас у нас используется метод `НовоеИмяФайла`
ИМХО имя этого метода не отвечает своему функционалу, т.к. возвращает не имя файла, а полный путь.
Возникает путаница с терминологией: у нас есть путь, полное имя, имя файла и есть метод, который должен возвращать имя, а возвращать полный путь/полное имя.

Предлагаю разделить функционал этого метода на два метода:
- `СлучайноеИмя` - получает именно имя нового файла, без пути к файлу
- `НовоеПолноеИмя` - получает именно полное имя нового файла, т.е. полный путь с именем файла

@EvilBeaver @nixel2007 @demidych что скажете?

**Comment by EvilBeaver** [comment]
1С - ПолучитьИмяВременногоФайла() возвращает ПолноеИмя. И никого не смущает. Ибо имя файла оно по-разному трактуется, в зависимости от контекста.

НовоеПолноеИмя - это хрень. Я вместо него предложил "Случайное" - без каталога. Ведь зачем вообще нужны все эти методы - быстро получить возможность записать какой-то файл, чтобы он не затер никакие существующие файлы, верно? 

Обычно такие файлы являются временными и лежат в tmp. @artbear утверждает, что есть сценарии, когда они лежат не в tmp - ладно, пусть. Тогда все равно, эти файлы имеют некое "случайное", "сгенерированное" имя, которое не пересекается с существующими файлами.

Что делает текущее API:

ВременныеФайлы.НовоеИмяФайлы - это обертка для ПолучитьИмяВременногоФайла(). Дает просто имя врем. файла, не создавая его. При этом регистрирует его в менеджере временных файлов, чтобы потом удалить. Т.е. "обертываемый" метод называется ИМЯ. И никого ничего не смущает и путаницы не вызывает.

НовоеПолноеИмя - бл#@ь ужоснах, пишу и мурашки по коже. Лучше уж "ИмяБезКаталога", а еще лучше вообще не выносить это в библиотеку, ибо слишком узкоспециализированный сценарий, в котором достаточно сделать `Новый Файл(ВременныеФайлы.НовоеИмяФайла()).Имя` И вынести это в метод - какой хотите. Но только в **клиентском скрипте**, а не в библиотеке.

Если очень хочется в библиотеку - то "СлучайноеИмя".

**Comment by EvilBeaver** [comment]
А еще идея посетила вот какая - Свойство "БазовыйКаталог" в классе МенеджерВременныхФайлов. Установил себе псевдо-temp папку и юзай библиотеку дальше, безо всяких "СлучайныхИмен".

**Comment by artbear** [comment]
По шагам:

> НовоеПолноеИмя - Лучше уж "ИмяБезКаталога", а еще лучше вообще не выносить это в библиотеку, ибо слишком узкоспециализированный сценарий, в котором достаточно сделать Новый Файл(ВременныеФайлы.НовоеИмяФайла()).Имя И вынести это в метод - какой хотите. Но только в клиентском скрипте, а не в библиотеке.

Тогда в каждом подобном клиентском скрипте придется помимо `Новый Файл(ВременныеФайлы.НовоеИмяФайла()).Имя` еще добавлять удаление полученного временного файла как `ВременныеФайлы.Добавить(ПолноеИмяВременногоФайла)` для его автоудаления.

> Свойство "БазовыйКаталог" в классе МенеджерВременныхФайлов. Установил себе псевдо-temp папку и юзай библиотеку дальше, безо всяких "СлучайныхИмен".

Интересно, мне и этот вариант нравится :)
Под мой сценарий он подходит.

Единственно, что становится не так удобно, когда есть некая иерархия подобных каталогов.

Например, в моем тесте конвертации мне понадобилось создать разные временные файлы в разных каталогах - ну вот такая задача была :)

В варианте с `БазовыйКаталог` придется переключаться туда и обратно при помощи этого свойства, что логично.

В общем, меня устраивает вариант с этим свойством.

Народ, что скажете?

**Comment by awa15** [comment]
Тогда уж, имхо, проще добавить второй параметр в `НовоеИмяФайла`

```
Функция НовоеИмяФайла(Знач Расширение = "tmp", Знач Каталог = "") Экспорт
```

Если второй параметр не указан, то поведение остается прежним, иначе временное имя файла создается в указанном каталоге, все остальное поведение остается прежним, т.е. этот файл также регистрируется в `мВременныеФайлы` для последующего удаления.

**Comment by artbear** [comment]
@awa15 Да, похоже, что это лучший вариант, раз уж @EvilBeaver считает, что название соответствует назначению.

@EvilBeaver принимаем в итоге?

**Comment by EvilBeaver** [comment]
Нет, не принимаем. До компа доберусь, напишу. Вкратце - менеджеров временных файлов может быть много, просто один - глобальный. А так, это класс, его можно через Новый создавать. См. внутрь пакета

**Comment by EvilBeaver** [comment]
Как мне все это видится: есть класс `МенеджерВременныхФайлов` Его назначение - управлять некоторым пулом временных файлов (и каталогов), которые потом можно автоматически удалить. Менеджер занимается отслеживанием создаваемых врем. файлов.

В моем миропонимании - временный файл это абстракция. Это файл "где-то", я не хочу знать где. Я хочу получить просто "файл" в собственное пользование и знать, что:
- Права на запись в этот файл у меня будут
- Место на диске там будет в наличии (как минимум, на 100-200Мб я могу рассчитывать)
- Файл не будет конфликтовать по имени с существующими в этом расположении другими файлами.

Для того, чтобы удовлетворить некие технические ограничения, я согласен с тем, что расположение этих временных файлов нужно регулировать (выбирать диск, каталог, etc).

Теперь, возвращаясь к задаче @artbear:

> Cоздать исходный временный каталог в системном временном каталоге я могу, далее в этом новом временном каталоге мне нужно сохранить файлы из макета, выдав файлу временное имя, и создать дополнительные доп.каталоги с временным именем, в которых также нужно сохранить файлы из макета, выдав файлу временное имя.

Я говорил ранее и повторю еще - это попытка использовать инструмент (библиотеку tempfiles) не по назначению. Назначение - описано выше - **абстрагирование от расположения** временного файла. А здесь же его, наоборот, требуется **конкретизировать**. Это не должно решаться на уровне библиотеки tempfiles.

У меня тоже были подобные задачи, их можно решить либо "в лоб", через УникальныйИдентификатор, либо рекурсивно добавляя числовой префикс, как это было сделано в ранних версиях v83unpack.os.

Это можно решить и множеством МенеджеровВременныхФайлов, но это нецелевое применение этой библиотеки. В любом случае, предложенная задача - это **узкоспециальный кейс**, который не должен решаться библиотекой общего назначения.

Итого:
- Я согласен, что нужно задавать БазовыйКаталог (см. пункт 2 в первом списке)
- Я согласен, что метод СлучайноеИмя может быть полезен, в том числе, в сценарии @artbear. Хотя, мне этот метод в библиотеке и не нравится.
- Я против добавления параметров к методу `ВременныеФайлы.НовоеИмяФайла`, ибо я, как пользователь, с помощью tempfiles как раз-таки не хочу думать в каком каталоге создавать файл.
- Имя `ВременныеФайлы.НовоеИмяФайла` соответствует своему поведению, ибо оно просто перефразирует 1С-овское `ПолучитьИмяВременногоФайла()`

**Comment by awa15** [comment]
@EvilBeaver , все рассуждения о том, нужно или не нужно задумываться о каталоге временного файла можно точно так же распространить на рассуждения о расширении временного файла. Однако в методе `ВременныеФайлы.НовоеИмяФайла` есть параметр `Расширение` (которое имеет значение по умолчанию для тех, кто не хочет задумываться о расширении). Дополнительный параметр `Каталог` точно так же имеет значение по умолчанию, и тем кому не надо, не будут о нем задумываться.
Если таким образом сравнивать параметры `Расширение` и `Каталог` метода `ВременныеФайлы.НовоеИмяФайла`, то единственным различием остается только то, что 1С в своем методе `ПолучитьИмяВременногоФайла()` добавила параметр `Расширение`, а параметр `Каталог`, к несчастью для @artbear , не добавила. Но это же не аргумент!
Сама заявленная цель класса `МенеджерВременныхФайлов`, "абстрагирование от расположения", имхо, не верна. Цель должна быть предоставить удобный интерфейс для работы с временными файлами, при этом позволяя как не задумываться о расположении и прочих внутренностях (для любителей автоматов и вариаторов), так и взять контроль в свои руки (для любителей механики).

**Comment by artbear** [comment]
> Сама заявленная цель класса МенеджерВременныхФайлов, "абстрагирование от расположения", имхо, не верна. Цель должна быть предоставить удобный интерфейс для работы с временными файлами, при этом позволяя как не задумываться о расположении и прочих внутренностях (для любителей автоматов и вариаторов), так и взять контроль в свои руки (для любителей механики).

+1

Ага, мне казалось, что мы для достижения этой цели и сделали данную библиотеку.

**Comment by EvilBeaver** [comment]
@awa15 ну вот тебе как часто нужно создавать временные файлы (с рандомными именами), но не во временном каталоге? И для каких задач?

ну и "взять контроль в свои руки" он для чего? Каков сценарий применения?

**Comment by awa15** [comment]
Вот у вас тут есть универсальная отмазка на все случаи жизни "каков сценарий?". А какой сценарий, что возникнут какие-то проблемы, если будет доп. параметр "Каталог" со значением по умолчанию?
Не из onescript: любой разбор файлов cf, 1cd, dt и т.д. влечет за собой массовые промежуточные операции inflate во временные файлы. Так как файлов бывает очень много, стандартный временный каталог, в котором и без меня файлов до фига, начинает просто тормозить. Поэтому я создаю отдельные временные каталоги (во временном же каталоге) где и создаю массово свои временные файлы.

**Comment by artbear** [comment]
@awa15 ага, фактически это описанный мной сценарий.
который совсем не редкость для скриптов!

**Comment by EvilBeaver** [comment]
@awa15 про сценарии спрашивается не просто же так. Они основа любого проектирования. Чтобы что-то делать, надо понимать _зачем_ и _для кого_. Возьмем, опять же, то, что ты описал - свой каталог и в него помещение файлов. Это прекрасно ложится в схему с "БазовымКаталогом". А если это будет параметр, то этот параметр тебе нужно вставлять в каждый вызов, хотя, значение будет всегда одно и то же. То есть, понимание сценария (твоего в данном случае) дает возможность сделать более удобный API специально под твою задачу.

**Comment by artbear** [comment]
На самом деле в моей задаче у меня была некоторая вложенность файлов/каталогов, поэтому в случае с БазовымКаталогом пришлось бы либо постоянно переключать его, что не красиво, либо создать специальный новый экземпляр Новый ВременныйФайлы и указывать базовый каталог, что красивее.

А в случае с `НовоеИмяФайла(Знач Расширение = "tmp", Знач Каталог = "")` переключение делать бы не пришлось :)

**Comment by awa15** [comment]
@EvilBeaver , я понимаю, что сценарии нужны. Но предусмотреть сразу все на свете все равно невозможно. А что плохого в чуть большей универсальности, которая не стоит почти ничего? Кто мешает добавить и `БазовыйКаталог` в класс, и доп. параметр `Каталог` в `НовоеИмяФайла`?
Чем же все-таки `Расширение` отличается от `Каталог`?

**Comment by EvilBeaver** [comment]
@awa15 ну отличается тем, что пользователь часто хочет создать файл "некоторого типа". В принципе, это не сильно нужно, но я могу себе представить сценарии, когда оно надо. Каталог - тоже похоже, но все-таки про другое.

```
Справка = ПолучитьИмяВременногоФайла("html");
ЗаписатьТекстСправки(Справка); // где-то формируем контент
ЗапуститьПриложение(Справка); // Открываем браузер (система поймет на основе расширения)
```

**Comment by artbear** [comment]
Продолжим? :)
Какие варианты остались?
Что выберем?

**Comment by EvilBeaver** [comment]
Я за вариант:
- в классе МенеджерВременныхФайлов создаем опцию "базовый каталог", относительно которого будет работать менеджер (вместо %TMP%)

**Comment by artbear** [comment]
4 месяца согласовываем.
Предлагаю уже остановиться :)

В целях завершения соглашусь с вариантом @EvilBeaver 
- в классе МенеджерВременныхФайлов создаем опцию "базовый каталог", относительно которого будет работать менеджер (вместо %TMP%)

**Comment by artbear** [comment]
Даже уже 6 месяцев

**Comment by artbear** [comment]
Жду ответа от @nixel2007 @awa15 @pumbaEO @demidych + других заинтересованных перцев :)

**Comment by EvilBeaver** [comment]
@artbear да вроде и так уже все согласны

**Comment by artbear** [comment]
Это было последнее китайское предупреждение :)

**Comment by artbear** [comment]
@EvilBeaver Почти все хорошо, кроме того, что у временных файлов есть модуль `ВременныеФайлы` и есть класс `МенеджерВременныхФайлов`.
По классу вопросов нет, а вот по использованию модуля есть.

Сейчас у нас появилась возможность именно у модуля `ВременныеФайлы` задавать экспортную переменную `БазовыйКаталог`.
В итоге 2 пользовательских класса могут устанавливать `ВременныеФайлы.БазовыйКаталог` и пытаться получать имена временных файлов, что может привести к ошибкам в случае перекрытия использования.

Что с этим будем делать?

**Comment by EvilBeaver** [comment]
ненене. Есть только класс МенеджерВременныхФайлов. И один экземпляр этого класса сразу доступен в глобальном контексте под именем ВременныеФайлы.

Таким образом, ты можешь создать несколько менеджеров временных файлов (каждый со своим списком) и точечно управлять удалением временных файлов, хранящихся в менеджере. По твоему вопросу: если ты создал отдельного менеджера, то БазовыйКаталог ты должен задавать ему.

**Comment by EvilBeaver** [comment]
Блин, я понял твой вопрос )
В случае перекрытия мы ничего делать не будем. Затем и добавлен класс, чтобы было хоть какое-то разделение ресурсов между модулями разных авторов. Надо писать так, чтобы не было единоличного захвата ВременныхФайлов, про который другие модули не знают.

**Comment by artbear** [comment]
Раньше у класса не было состояния.
Теперь оно появилось и синглтон юзать уже не так безопасно

чт, 7 Июл 2016, 8:28 Andrei Ovsiankin notifications@github.com:

**Comment by EvilBeaver** [comment]
@artbear раньше тоже было - внутренний список врем файлов. И нечаянное ВременныеФайлы.Удалить() грохало их все, хотя, возможно, какой-то другой модуль их еще собирался пользовать. Глобальный объект в библиотеках - зло, надо его убирать. Он для разовых скриптов, чтобы синтаксис проще был. Короче, сейчас безопасность не ухудшилась, а так и осталась не очень хорошей.
