### ISSUE TITLE
json: Добавить возможность настройки объекта (АвтоматическоеПриведениеОбъектаКСтруктуре и т.п.)

### ISSUE THREAD

**Issue by kuntashov** [EvilBeaver/oscript-library#44]
В исходной обработке, на основе которой сделана библиотека, настройка объекта предполагает "хардкод" параметров, например, есть параметр `АвтоматическоеПриведениеОбъектаКСтруктуре`, по умолчанию его значение - `Ложь`.  

Изменить эту настройку никак нельзя, кроме как поменять жестко захардкоженое в функции `НастройкаАвтоматическоеПриведениеОбъектаКСтруктуре()` возвращаемое значение (Ложь на Истина), что неприемлемо для библиотеки общего назначения, коей является данная библиотека.

Необходимо для следующих настроек, описанных в документации библиотеки, сделать так, чтобы их можно было бы менять из клиентских скриптов:
- `АвтоматическоеПриведениеОбъектаКСтруктуре`
- `НеявноеПриведениеПримитивныхЗначенийКлюча`
- `ПолноеМаскированиеСимволов`
- `МаскированиеКириллицы`

**Comment by kuntashov** [comment]
Я готов сам реализовать описанную доработку.

Концепция решения:
1. В метод  `ПрочитатьJSON()` добавить дополнительный аргумент `АвтоматическоеПриведениеОбъектаКСтруктуре`, значение по умолчанию - `Ложь`
2. В метод `ЗаписатьJSON()` добавить дополнительные аргументы `НеявноеПриведениеПримитивныхЗначенийКлюча`, `ПолноеМаскированиеСимволов`, `МаскированиеКириллицы` (значение по умолчанию соответственно `Ложь`, `Истина`, `Ложь`) 
3. Обеспечить использование значений этих аргументов вместо использования методов вида `Настройка*` везде в коде.

Я также рассматривал возможный альтернативный вариант, который реализовать проще:
1. Добавить экспортные свойства (переменные), одноименные с настройками, устанавливать их значения по умолчанию в блоке основной программы.
2. В методах `Настройка*` вместо захардкоженных значений возвращать значения соответствующих свойств.

Но этот вариант плох тем, что настройки будет действовать "глобально" между разными сеансами вызова методов `ПрочитатьJSON`/`ЗаписатьJSON`, а как я посмотрел в существующем коде, принято создавать экземпляр объекта ПарсерJSON однократно и далее многократно его использовать. 

Ну и в целом исходная архитектура объекта сделана stateless, видимо, чтобы ее можно было использовать как общий модуль в конфигурации и, к слову, было бы лучше и в стандартной библиотеке 1Script его не как класс реализовать, а как модуль, но это не критично.

**Comment by kuntashov** [comment]
Вот здесь сделал https://github.com/kuntashov/oscript-library/tree/feature/json-settings + нашел и исправил один небольшой баг, на все написал тесты, готов сделать pull-request.

**Comment by artbear** [comment]
Готов, делай.
Пулл-реквестам всегда дорога открыта

пт, 1 Янв 2016, 20:41, Alexander Kuntashov notifications@github.com:
