### ISSUE TITLE
readme.md: Исправить описание библиотеки strings

### ISSUE THREAD

**Issue by kuntashov** [EvilBeaver/oscript-library#45]
В описании библиотеки strings написано

> Работа со строками. Фактически является копией общего модуля "СтроковыеФункцииКлиентСервер" из поставки Библиотеки Стандартных Подсистем.

Смущает слово "копия", предлагаю заменить слово "аналог" или более явно написать: "API библиотеки совместимо с API модуля СтроковыеФункцииКлиентСервер из БСП".

**Comment by artbear** [comment]
Согласен

пт, 1 Янв 2016, 20:58, Alexander Kuntashov notifications@github.com:
