### ISSUE TITLE
gitsync Ошибка подгрузки библиотеки "core"

### ISSUE THREAD

**Issue by JohnyDeath** [EvilBeaver/oscript-library#52]
Не выполняется скрипт gytsync. Вываливает ошибку:

> {Модуль e:\Repos\oscript-library\src\gitsync\src\gitsync.os / Ошибка в строке: 10 / Библиотека не найдена "core"}

Это строка звучит так:
`#Использовать "core"`
Каталог core состоит из двух подкаталогов: "Классы" и "Модули". 
Так и должно быть? Использую 1script самый последний 1.0.11.53

Запускаю всё из локального свежего гит-репозитория.
Строка запуска:
`oscript gitsync.os help init`

Что я делаю не так?

**Comment by EvilBeaver** [comment]
Странно, у меня работает. Посмотри, у тебя в oscript.cfg какой путь к библиотекам прописан? Он корректный?

Это если мы про 1.0.11.53 говорим.

**Comment by JohnyDeath** [comment]
```
#Конфигурационный файл OneScript

# Корневой каталог системных библиотек
lib.system = ../lib

#Дополнительные каталоги поиска библиотек
#lib.additional = C:\somedir;C:somedir2;
```

Но вроде как директива 
`#Использовать "core"`
говорит о том, чтобы поиск начался в каталоге скрипта. Нет?
Если пишу 
`#Использовать "core/Классы"`
тогда подгружается, но ес-но только классы

**Comment by JohnyDeath** [comment]
Если меняю эту строку на

```
#Использовать "core/Модули"
#Использовать "core/Классы"
```

Тогда вот такая ошибка:

> ОШИБКА - {Модуль e:\tmp\2\gitsync.os / Ошибка в строке: 46 / Слишком много фактических параметров}

У меня явно что-то не так..

**Comment by JohnyDeath** [comment]
Вообще не совсем понятно как должны обновляться "стандартные" библиотеки.
Как я понимаю, тот же "парсер" подгружается из каталога, куда установлен oscript.exe. А он отличается от того, что сейчас есть в текущем репо.
Руками все перезаписать? Какой правильный сценарий обновления?

**Comment by nixel2007** [comment]
В 1.0.11 подключение "по имени"  вообще не ищет в каталоге скрипта.

**Comment by JohnyDeath** [comment]
В общем победил так.
В каталоге, куда установлен oscript.exe ищем каталог "lib". Все его содержимое удаляем (перемещаем в другое место) и туда копируем содержимое этого репозитория из каталога "src".
И все заработало, включая правильную подгрузку core

Эту же проблему можно решить не так радикально, поменяв в %OneScriptDir%\bin\oscript.cfg путь 
lib.system = ../lib
на каталог, где у вас текущий репо

В общем, вопрос обновления стандартных библиотек остается открытым

**Comment by nixel2007** [comment]
> В каталоге, куда установлен oscript.exe ищем каталог "lib". Все его содержимое удаляем (перемещаем в другое место) и туда копируем содержимое этого репозитория из каталога "src".
> И все заработало, включая правильную подгрузку core

Собственно, я всегда так и делал... :)
Так же можешь посмотреть на вот эту issue https://bitbucket.org/EvilBeaver/1script/issues/201
Скоро можно будет и локальные библиотеки по имени подключать.

**Comment by EvilBeaver** [comment]
@JohnyDeath ну как бы да, оно так и обновляется. Вот мне бы еще одни рабочие руки, чтобы доделать, наконец, автосборки библиотек и выкладывания на hub. Тогда обновление библиотек будет делаться через `opm update gitsync`
