### ISSUE TITLE
gitsync: Хак для исправления ошибки распаковки

### ISSUE THREAD

**Issue by theshadowco** [EvilBeaver/oscript-library#55]
Добрый день.

_При распаковке одного из хранилищ возникла ошибка 
Ошибка преобразования данных XDTO:
Запись значения свойства:
форма: Элемент
имя: {http://v8.1c.ru/8.2/data/spreadsheet}document
по причине:
Ошибка преобразования данных XDTO:
Запись значения свойства:
форма: Элемент
имя: {http://v8.1c.ru/8.2/data/spreadsheet}table
по причине:
Ошибка отображения типов:
Отсутствует отображение для типа 'СводнаяТаблица'_

Опытным путем пришел к решению, в рамках которого добавил еще один параметр гитсинку. При наличии этого параметра производится распаковка cf средствами unpackv8 и удаляется лишняя информация из cf. После этого произвожу обратную упаковку и продолжаю синк. 

Есть ли более элегантное решение? 
Интересно ли описанное (могу прислать пулл реквест)?

**Comment by EvilBeaver** [comment]
А что конкретно распаковывается и удаляется из метаданных?

**Comment by theshadowco** [comment]
Распаковывыется файл конфигурации (cf целиком), выгруженный из хранилища tool_cd. В каталоге по содержимому по идентификатору типа "СводнаяТаблица" находится макет xml и удаляется. CF после сборки отлично открывается, удаленный макет в ней присутствует (пустой). 

Можно не удалять файл, а очищать например.

**Comment by theshadowco** [comment]
Для распаковки используется строка вида "unpackv8.exe -parse vn.cf tempdir"

**Comment by nixel2007** [comment]
У вас не версия платформы для обучения, случаем?
Там нет поддержки сериализации сводной таблицы.

**Comment by theshadowco** [comment]
нет, полная. пробовал и на 8.3.6 и 8.3.7

**Comment by theshadowco** [comment]
конфа (из хранилища) в совместимости с 8.1. вручную ставил различные режимы и руками же нажимал кнопку выгрузить - все равно падал

**Comment by JohnyDeath** [comment]
Надо б сделать минимальный cf с повторяющейся ошибкой и зарегистрировать баг в 1С

**Comment by theshadowco** [comment]
@JohnyDeath  cf готов сделать, вот зарегать не могу - нет договоров с франями/партнерами (актуальных на сегодня, придется ждать)

**Comment by JohnyDeath** [comment]
@theshadowco кидай мне, помогу чем смогу

**Comment by theshadowco** [comment]
Порядок действий:
 - Создать базу
 - Загрузить
 - сохранить
 - нажать выгрузить в файлы

С уважением,
Максимов Валерий.
maximovvalery@gmail.com

2016-01-13 23:40 GMT+03:00 Evgeny Martynenkov <notifications@github.com>:

**Comment by theshadowco** [comment]
Конфа с ошибкой

С уважением,
Максимов Валерий.
maximovvalery@gmail.com

2016-01-13 23:40 GMT+03:00 Evgeny Martynenkov notifications@github.com:

**Comment by JohnyDeath** [comment]
нет вложения.
На почту кинь. Мой ник на гмыле

**Comment by theshadowco** [comment]
Отправил

**Comment by artbear** [comment]
@JohnyDeath что скажешь по ошибке? это проблема конкретной конфигурации?

**Comment by theshadowco** [comment]
@artbear Повторяется на любой конфе

**Comment by theshadowco** [comment]
@artbear Сценарий
- Создать базу с пустой конфигурацией
- Добавить общий макет 
- Вставить в общий макет сводную таблицу
- Сохранить изменения
- Запустить выгрузку в исходные файлы
- Получить ошибку

**Comment by nixel2007** [comment]
/offtopic
даже не замечал до этого, что в общие макеты можно вставлять сводные таблицы... как-то никогда не требовалось :)

**Comment by theshadowco** [comment]
@nixel2007 Это для сценария я указал общий макет, в моем грустном случае это был отчет.

**Comment by JohnyDeath** [comment]
В 1с писал. Последний ответ от них был 18 января следующего содержания

```
Здравствуйте!
Ваше обращение зарегистрировано под номером SW1000482 / 1.
Пожалуйста, в тексте следующих обращений на эту же тему ссылайтесь на этот номер.

   Ваше сообщение переадресовано в отдел разработки программ.
   Ответ разработчика будет выслан Вам дополнительно.
```

Сейчас вот решил проверить в зарегистрированных. Таки есть: https://bugboard.v8.1c.ru/error/000012486.html
Приняли к исправлению.

Как говориться: "Подписывайтесь, ставьте лайки" (на ошибку в 1С можно подписаться)

**Comment by EvilBeaver** [comment]
Не вижу смысла исправлять средствами gitsync, тем более, "вырезанием" проблемного фрагмента.

**Comment by srustamo** [comment]
@JohnyDeath Статус обновился бага? Тоже нет доступа к багтреккеру 1С. Если интересны детали (может обновите багрепорт): 
- полная версия 1С 8.3.7.1776
- при выгрузке файлов конфигурации из конфигуратора (Конфиграция - Выгрузить конфигурацию в файлы) спотыкается с ошибкой в первом посте этого треда
- общего макета нет, но есть макеты в документах
- не помню, что включал сводные таблицы, есть двоичный и ActiveDocument макеты эксель в одном из документов

**Comment by srustamo** [comment]
@theshadowco Как вы определили в каком объекте метаданных происходит ошибка? Из ошибки не видно.

**Comment by JohnyDeath** [comment]
@srustamo 

> Исправлена: "Технологическая платформа", версия 8.3.8.1652
