### ISSUE TITLE
gitsync: Формирование комментария коммита

### ISSUE THREAD

**Issue by theshadowco** [EvilBeaver/oscript-library#56]
При формировании комментария коммита гитсинк использует комментарий хранилища. Не секрет, он часто бывает пустым, но при этом метка в хранилище может быть заполнена (и содержать описание коммита).

Как смотрите на это с высоты своего опыта? Может стоит формировать комментарий например как (схематично):
_Комментарий = КомментарийХранилища;
Если Пустаястрока(МеткаХранилища) Тогда 
Комментарий = МеткаХранилища + ?(ПустаяСтрока(Комментарий), "", Символы.ПС + Комментарий);
Если ПустаяСтрока(Комментарий) Тогда
Комментарий = ".";
КонецЕсли_

**Comment by EvilBeaver** [comment]
Метка как раз еще чаще не заполнена. А если заполнена, то не факт, что она отражает суть коммита. Как правило там написано то, что в гите называется словом _tag_ - там, как правило пишут, что, мол, вот этот коммит - это версия 1.0.1.1 или там, "стабильный релиз" или еще что-то. Иными словами, добавление текста метки в коммит не сильно поможет, а скорее даже и запутает.

ИМХО.

**Comment by artbear** [comment]
Согласен с @EvilBeaver, что метка используется намного реже.
Мы ее юзаем именно как tag

@theshadowco Согласен с нами?
Если да, закроем issue ?
Если нет, пиши, обсудим дальше.

**Comment by theshadowco** [comment]
Отчасти согласен. 
У меня просто несколько хранилищ, в которых в метку писался каммент к задаче. Как тэг тож использовать не получится, ибо есть примеры. когда метка содежит по сути несколько тэгов.

**Comment by theshadowco** [comment]
Давайте закроем задачу, спасибо за ответы
