### ISSUE TITLE
v8runner: Перед выполнением команд 1С нужно проверять существование файла платформы 1С

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#60]
Перед выполнением команд 1С нужно проверять существование файла платформы 1С

Сейчас при указании неверного пути к платформе выдается малопонятное сообщение 

```
{Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / 
Ошибка в строке: 484 / Внешнее исключение: Не удается найти указанный файл}
[12:11:43][Step 2/10] Process exited with code 1
```

**Comment by EvilBeaver** [comment]
И пусть выдается. Не фиг указывать пути напрямую. Надо юзать метод "использоватьВерсиюПлатформы"

-----Исходное сообщение-----
От: "Artur Ayukhanov" notifications@github.com
Отправлено: ‎21.‎01.‎2016 20:42
Кому: "EvilBeaver/oscript-library" oscript-library@noreply.github.com
Тема: [oscript-library] Перед выполнением команд 1С нужно проверять существование файла платформы 1С (#60)

Перед выполнением команд 1С нужно проверять существование файла платформы 1С
Сейчас при указании неверного пути к платформе выдается малопонятное сообщение 
{Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / 
Ошибка в строке: 484 / Внешнее исключение: Не удается найти указанный файл}
[12:11:43][Step 2/10] Process exited with code 1

**Comment by artbear** [comment]
Не соглашусь. Уже есть куча скриптов, в которых явно передается путь к
платформе. Например, для ci таких полно. Апи раннера позволяет юзать такой
режим

чт, 21 Янв 2016, 22:07, Andrei Ovsiankin notifications@github.com:

**Comment by EvilBeaver** [comment]
Все равно. Это deprecated метод и не надо поощрять его использование

**Comment by nixel2007** [comment]
Может добавить deprecated сообщение, как ты это сделал для exception?

**Comment by EvilBeaver** [comment]
Наверное, можно сделать проверку в момент установки пути к платформе. Но не перед выполнением каждой команды. @artbear что скажешь?

**Comment by artbear** [comment]
Я бы проверял именно перед выполнением каждой команды.
ИМХО это наиболее правильно.
Тем более, что там уже есть проверка на заполненность пути к платформе, и нужно будет только добавить проверку на существование файла

**Comment by artbear** [comment]
@nixel2007

> Может добавить deprecated сообщение, как ты это сделал для exception? 

Пропустил, подскажите, что за сообщение

**Comment by nixel2007** [comment]
@artbear https://bitbucket.org/EvilBeaver/1script/commits/6ab98ec970a40f6b383de214923f5e0ca9c8814f

**Comment by artbear** [comment]
Меня интересует именно исключение с внятным текстом, а не простое сообщение.

**Comment by EvilBeaver** [comment]
@artbear скажи, зачем оно тебя интересует именно в момент выполнения? Ты установил версию платформы, установил криво. Зачем тебе получать сообщение в момент команды? Логично, если ты получишь его в момент установки кривого значения.

**Comment by artbear** [comment]
@EvilBeaver Лады, я посмотрел код, уговорили.
Нужно добавить проверку на существование файла в 2 метода `ПутьКПлатформе1С` и `ПутьКТонкомуКлиенту1С`
