### ISSUE TITLE
Contribution guideline

### ISSUE THREAD

**Issue by g-ones** [EvilBeaver/oscript-library#62]
собственно нужно как-то определиться с положением о контрибьюции

что имеется ввиду:
- я хочу добаработать скрипт v8runner - у меня есть 2 команды и тесты на них которые я сделал для себя
- дорабатывал я естественно напрямую в **oscript_install_path**\lib 

теперь придется копировать свои доработки в отдельный git клон данного репозитория и делать пул-реквест.

я то разобрался (правда потратил 3 часа), но остальным будет полезно иметь такой вот мануал

если бы был простой файлик CONTIBIUTION.md - было бы проще будущим падаванам DevOps

**Comment by EvilBeaver** [comment]
Файл с инструкцией добавлен.
