### ISSUE TITLE
gitsync: При уровне логгирования debug не удалять временные файлы

### ISSUE THREAD

**Issue by pumbaEO** [EvilBeaver/oscript-library#65]
Часто при работе с gitsync приходится отлаживать код, при этом временные файлы удаляются. Хотелось бы при режиме отладки, что-бы временные файлы не удалялись. В теории такой режим нужен только для отладки, поэтому остаточные артефакты - это необходимый функционал для полноценной отладки. Сейчас вроде в режиме отладки выводиться команда которая должна выполниться, но выполнить мы ее не можем, т.к. уже таких путей не существует.

**Comment by nixel2007** [comment]
Поддерживаю. Желательно для всех библиотек, а не только для gitsync

**Comment by EvilBeaver** [comment]
@nixel2007 насчет "для всех" вопрос спорный. Имхо, каждый пакет сам решит, как надо. А так, да, функционал полезный.

**Comment by artbear** [comment]
ИМХО для этой фичи должен быть отдельный ключ.
Зачем смешивать разные режимы работы - логирование и временные файлы ?

Например, у меня гитсинк всегда работает в режиме отладки, на CI очень удобно отслеживать полные логи. А вот оставлять временные файлы мне совсем не хочется.

**Comment by EvilBeaver** [comment]
@artbear +1

**Comment by theshadowco** [comment]
@artbear +1

**Comment by JohnyDeath** [comment]
Поддерживаю @artbear . У меня точно также работает. Приятно иной раз логи посмотреть (жалко, время туда не пишется)

**Comment by g-ones** [comment]
@pumbaEO может сюда https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/src/gitsync.os#L53

добавить другой флаг

```
--do-not-delete-tempfile
```

или как в Linux придумать режим --veryverbose

я к тому может это отдельный флаг ?

**Comment by theshadowco** [comment]
@JohnyDeath Да, реально времени не хватает. Надо issue запостить
@g-ones поддерживаю с отдельным флагом

**Comment by EvilBeaver** [comment]
Если не ошибаюсь, в gitsync уже есть флаг `-debug`
Кто сказал, что он должен регулировать только уровень лога? Он говорит, что включен "Отладочный режим". Который, как заметил @pumbaEO требует не удалять врем. файлы.

То есть, отдельный флаг не нужен. А вот тем, кому нравятся подробные логи нужно в logos реализовать функционал, которого там давно не хватает - конфигурационный файл в стиле log4j. Пользователь приложения указывает в конфиге - какой уровень логов хочет, а приложение такой уровень включает. Когда все хорошо логируются только, например, ошибки, а когда возникают проблемы - включают DEBUG. Так принято в большинстве приложений, использующих логирование.

Итого, предлагаю: 
- не вводить новый флаг, для "неудаления" файлов использовать существующий ключ -debug.
- для сценария "Подробных логов" завести issue на logos "Реализовать внешнее управление уровнем логирования по имени лога".

**Comment by EvilBeaver** [comment]
В качестве дополнения: можно завести в gitsync ключ --verbose, который тоже повысит "болтливость", то к отладке отношения иметь не будет и врем. файлы будут удаляться. Так тоже стандартно и общепринято.

Насчет ключа "--do-not-delete-tempfile" против категорически. Это раскрытие реализации и нарушение принципа инкапсуляции.

**Comment by artbear** [comment]
ИМХО изменение поведения ключа -debug и добавление нового ключа -verbose нужно делать одновременно.
Меня лично не особо порадует то, что временные файлы будут оставаться всегда.

**Comment by pumbaEO** [comment]
Имхо путаемся в уровнях логгирования, trace, debug, notice, info, warning, error, alert  и текущий режим debug используется как notice, поэтому и возникают споры.

**Comment by EvilBeaver** [comment]
@artbear мы с тобой что-то продолбали такое разнообразие уровней, когда logos писали :)

**Comment by artbear** [comment]
@EvilBeaver ты подзабыл: мы не продолбали, мы приняли взвешенное решение :) 
- для кода скриптов onescript пока не нужно столь большое разнообразие уровней.
- Если возникнет необходимость, доделаем, АПИ позволяет.

**Comment by EvilBeaver** [comment]
@artbear - хитрый представитель собственной национальности? Как дипломатично все подвел!

**Comment by artbear** [comment]
@EvilBeaver и национальность есть, и на самом деле так все и было при нашем парном программировании :)

**Comment by EvilBeaver** [comment]
Резюмирую: ключ debug должен включать режим, когда временные файлы не удаляются. Отладочные логи делаем через расширение logos.

**Comment by artbear** [comment]
@EvilBeaver не согласен.
В ветке мнения разделились.
Насколько я увидел, 2 голоса за совмещение дебаг-режима логирования и удаления временных файлов, а целых 3 голоса за отдельные флаги логов и временных файлов!

**Comment by artbear** [comment]
Или я тебя не понял.

**Comment by nixel2007** [comment]
Перечитав ветку:
1) За добавление ключа debug
2) Не вижу причин, почему не переводить логи в режим Отладка при включенном дебаг режиме

**Comment by EvilBeaver** [comment]
@nixel2007 по п.2 разумеется логи будут переводиться в debug. Но вот сейчас @artbear использует отладочный режим чисто для более подробных логов. Ему не захочется, чтобы у него временные файлы при этом накапливались. Вот для такого сценария нужна возможность настройки логов, не затрагивающая другие алгоритмы приложения.

**Comment by nixel2007** [comment]
@EvilBeaver @artbear есть еще такой ключ как --verbose (многоразовый), который повышает уровень выводимых сообщений.

Можно добавить два ключа. debug будет помогать отлаживать (файлы, логи, все подряд), а --verbose только повышать уровень лога.

**Comment by EvilBeaver** [comment]
verbose там тоже в переписке выше мелькал )

**Comment by nixel2007** [comment]
точно, пропустил :)

мне кажется, это оптимальный вариант (с двумя ключами)

**Comment by artbear** [comment]
Да, я также за вариант с 2мя ключами.
Возможно, @EvilBeaver предлагает также это решение, но я лично твое "резюмирую" не понял.

**Comment by EvilBeaver** [comment]
Ок, два ключа, но в logos функционал внешнего управления тоже нужен.

**Comment by artbear** [comment]
> но в logos функционал внешнего управления тоже нужен.

Расшифруй

**Comment by EvilBeaver** [comment]
@artbear в JAVA у тебя нет доступа к исходникам, чтобы в коде прописать

```
Лог.УстановитьУровень(УровниЛога.Отладка);
```

Поэтому рядом с приложением лежит файл конфига log4j, где ты можешь регулировать логи без перекомпиляции.

**Comment by nixel2007** [comment]
> Поэтому рядом с приложением лежит файл конфига log4j, где ты можешь регулировать логи без перекомпиляции.

да, это было полезно.

**Comment by EvilBeaver** [comment]
@nixel2007 там же регулируется куда писать логи - консоль, файл, субд и прочее и прочее

**Comment by artbear** [comment]
Функционал с файлом настройки мы сознательно отложили на будущее согласно принципу MVP

**Comment by artbear** [comment]
> Можно добавить два ключа. debug будет помогать отлаживать (файлы, логи, все подряд), а --verbose только повышать уровень лога.

Итак, у нас есть подходящий вариант.

Утрясем детали?
- эти 2 ключа взаимоисключащие, верно? или они могут использоваться одновременно?
- Если взаимоисключащие, то при включении ключа debug - файлы не удаляются, но нет подробных сообщений, верно? А при включении ключа verbose есть подробные сообщения, но файлы опять не удаляются или удаляются?

**Comment by nixel2007** [comment]
@artbear 
1) могут использоваться одновременно.
2) мое предложение - debug _и_ оставляет файлы _и_ повышает уровень до Отладка.
-verbose просто повышает уровень до Отладка

**Comment by artbear** [comment]
@nixel2007 ИМХО только такой вариант и возможен :)

**Comment by EvilBeaver** [comment]
Да, именно так

**Comment by nixel2007** [comment]
Беру на себя.

**Comment by nixel2007** [comment]
Немного погорячился :)

С корневым модулем gitsync проблем-то нет.
Пытаюсь придумать, как сделать красиво для класса МенеджерСинхронизации. У него внутри есть куча мест, где удаляются файлы. Хочется иметь некий единый флаг РежимОтладки и процедуру удаления файлов, которые были бы доступны и из gitsync.os и из МенеджерСинхронизации.os.

Как лучше организовать это добро? (@EvilBeaver)

**Comment by nixel2007** [comment]
Кандидат на функцию удаления файлов

``` bsl
Процедура УдалитьВременыеФайлыПриНеобходимости(Знач ПутьКФайлу = "")

    Если РежимОтладки Тогда
        Возврат;
    КонецЕсли;

    Если ПутьКФайлу = "" Тогда
        ВременныеФайлы.Удалить();
    Иначе
        ВременныеФайлы.УдалитьФайл(ПутьКФайлу);
    КонецЕсли;

КонецПроцедуры
```

**Comment by artbear** [comment]
@nixel2007 Шустрый ты.
Я также эту функциональность меняю :)
я такой вариант придумал для инициализации

```
Функция ПолучитьИНастроитьРаспаковщик(Знач Параметры)
    Распаковщик = ПолучитьРаспаковщик();
    Распаковщик.ДоменПочтыДляGitПоУмолчанию = Параметры["-email"];
    УстановитьРежимОтладкиПриНеобходимости(Параметры);
    УстановитьРежимУдаленияВременныхФайлов(Параметры);
    Распаковщик.УстановитьПризнакУдаленияВременныхФайлов(НужноОставлятьВременныеФайлы());
    Возврат Распаковщик;
КонецФункции
```

А уже в менеджере меняю все ВременныеФайлы.УдалитьФайл на вызов единого метода УдалитьВременныеФайлыПриНеобходимости()

Я свою ветку закрываю, раз ты даже пуш успел сделать :)

**Comment by artbear** [comment]
> С корневым модулем gitsync проблем-то нет.
> Пытаюсь придумать, как сделать красиво для класса МенеджерСинхронизации. У него внутри есть куча мест, где удаляются файлы. Хочется иметь некий единый флаг РежимОтладки и процедуру удаления файлов, которые были бы доступны и из gitsync.os и из МенеджерСинхронизации.os.
> 
> Как лучше организовать это добро? (@EvilBeaver)

Можно сделать спец.класс, который будет отвечать за удаление временных файлов и который можно будет инициализировать состоянием параметров запуска.
В итоге объект класса создается в gitsync.os, а затем передается в МенеджерСинхронизации.

**Comment by nixel2007** [comment]
> Это может быть отдельный класс, который создается в gitsync.os, а затем передается в МенеджерСинхронизации.

Пробовал внутри папки core создавать класс `Отладка`. gitsync вроде как подключает всю папку `core`. А вот из менеджера синхронизации этот класс недоступен =/

> Но ИМХО проще в МенеджерСинхронизации передать сам объект gitsync через ЭтотОбъект, 

я думал об этом, но кажется, что это как-то... попахивает.

**Comment by artbear** [comment]
> > Это может быть отдельный класс, который создается в gitsync.os, а затем передается в МенеджерСинхронизации.
> 
> Пробовал внутри папки core создавать класс `Отладка`. gitsync вроде как подключает всю папку `core`. А вот из менеджера синхронизации этот класс недоступен =/

Нам класс нужен в gitsync для создания объекта и его настройки. А в менеджер синхронизации мы передадим уже готовый объект.
Поэтому тут проблем не вижу.

> > Но ИМХО проще в МенеджерСинхронизации передать сам объект gitsync ез ЭтотОбъект, 
> 
> я думал об этом, но кажется, что это как-то... попахивает.

Из-за подобного запаха я сразу же и удалил это свое предложение

**Comment by EvilBeaver** [comment]
> Как лучше организовать это добро?
1. Заводим в МенеджереСинхронизации метод РежимОтладки(ВклВыкл)
2. Из управляющего модуля читаем параметры и если надо вкл. режим отладки
3. Внутри МенеджераСинхронизации делаем рефакторинг, выносим все удаления в единый метод, примерно, как написал @nixel2007 (я в код не лазил, точное решение не скажу)
4. Введение каких-то новых классов это, имхо, over-engineering на данном этапе.

**Comment by artbear** [comment]
@nixel2007 Как у тебя дела с этой доработкой? уже 2 недели прошло :)

**Comment by nixel2007** [comment]
@artbear опен-сорс жи)
оно у меня висит в списке ToDo. Если кому-то нужна реализация "прям щас", то я не обижусь, если меня опередят)

**Comment by artbear** [comment]
@nixel2007 ты же шустрый, поэтому я посчитал, что поскольку ты начал работу, быстро ее и закончишь :)

**Comment by ghost** [comment]
@EvilBeaver прикрути ZenHub, чтобы можно было перетаксивать по статусам.

UPD - Увидел что прикручено

**Comment by artbear** [comment]
@EvilBeaver как дела с реализацией? будешь делать?

**Comment by EvilBeaver** [comment]
Ну если есть желание взять - я против не буду

**Comment by artbear** [comment]
@EvilBeaver лады, я сделаю.
