### ISSUE TITLE
fluent API для CMDLINE

### ISSUE THREAD

**Issue by EvilBeaver** [EvilBeaver/oscript-library#66]
Оставляю, как напоминалку, задокументирую позже.
Суть: текущий API cmdline сложноват.
Предложение:

```
Парсер.ДобавитьПараметр("Путь")
    .Обязательный()
    .Описание("Укажите путь к файлу")
    .Именованный("-file");
```

В командной строке:

```
someapp -file /home/user/file.txt
```

В коде чтения параметров:

```
Сообщить(ПараметрыКомСтроки.Путь);
```

**Comment by EvilBeaver** [comment]
P.S. возможно даже другим пакетом `cmdline-fluent`

**Comment by artbear** [comment]
Ага, хорошая тема.
Поддерживаю идею другого пакета.

**Comment by nixel2007** [comment]
Реализовано в виде библиотеки cli

**Comment by EvilBeaver** [comment]
В приципе, да.
