### ISSUE TITLE
v8runner: Возможность указания произвольного имени файла вывода логов от 1С:Предприятие

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#71]
Возможность указания произвольного имени файла вывода логов от `1С:Предприятие/Конфигуратор`

Например, когда идет несколько запусков Конфигуратора и Предприятия подряд, происходит неприятное:
- логи от всех 1С пишутся в один и тот же log.txt
- В итоге последний запуск в режиме Конфигуратора/Предприятия затирает все логи и файл лога всегда пуст

**Comment by JohnyDeath** [comment]
Поддерживаю. Полезная штука.

**Comment by nixel2007** [comment]
Удобненько!
