### ISSUE TITLE
logos: Немедленный вывод строки в файл лога без использования промежуточного буфера

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#77]
Часто бывает ситуация, когда скрипт зависает на середине выполнения.
Текущего механизма вывода в консоль и в отдельный лог-файл недостаточно.
- Скрипт может быть запущен из другого скрипта, не из консоли, и у нас нет доступа к сообщениям скрипта
- Вывод в отдельный лог-файл сейчас реализован с использованием промежуточного буфера. В случае зависания скрипта вывод в лог-файл не происходит.

Предлагаю добавить плагин для немедленного вывода строки в файл лога без использования промежуточного буфера.

В итоге даже при зависании скрипта лог-файл все равно будет заполнен.

@EvilBeaver Что скажешь?

**Comment by nixel2007** [comment]
Я думал, что аппендер на каждый вызов Информация() сразу дописывает в файл.
Иначе это не аппендер какой-то...

**Comment by artbear** [comment]
Вот и мне не нравится :)

https://github.com/EvilBeaver/oscript-library/blob/develop/src/logos/src/file-appender.os

```
Перем мФайлЛога;

Процедура ОткрытьФайл(Знач Путь, Знач Кодировка = "utf-8", Знач Добавлять = Истина) Экспорт
    мФайлЛога = Новый ЗаписьТекста(Путь, Кодировка,,Добавлять);
КонецПроцедуры

Процедура Вывести(Знач Сообщение) Экспорт
    ПроверитьИнициализацию();
    мФайлЛога.ЗаписатьСтроку(Сообщение);
КонецПроцедуры

Процедура Закрыть() Экспорт
    ПроверитьИнициализацию();
    мФайлЛога.Закрыть();
    мФайлЛога = Неопределено;
КонецПроцедуры

Функция ПроверитьИнициализацию()
    Если мФайлЛога = Неопределено Тогда
        ВызватьИсключение "Не открыт файл лога";
    КонецЕсли;
КонецФункции
```

**Comment by artbear** [comment]
Я для своих проектов изменял этот класс на немедленную запись и закрытие файла

**Comment by EvilBeaver** [comment]
В oscript специально для этого вводилось выключение буферизации. Т.е. сейчас (на стабильной версии 12) вывод должен быть немедленным сразу после ЗаписьТекста.Записать()

Какая версия односкрипта?

https://bitbucket.org/EvilBeaver/1script/commits/bcaa0251345a0636aa2ce200ac6a67603b07ff9c

**Comment by artbear** [comment]
Насколько я помню, в коде юзается ЗаписатьСтроку, а не Записать.
@EvilBeaver ты про какой вариант говоришь?

Конечно, я юзал на новой версии.
А тесты на новое поведение ЗаписьТекста есть?

чт, 24 Мар 2016, 18:01 Andrei Ovsiankin notifications@github.com:

**Comment by EvilBeaver** [comment]
Давай лучше ты дашь мне воспроизведение. Я проверял автоflush буфера, он работает. По крайней мере на простейших примерах. Как воспроизвести ошибку?

**Comment by artbear** [comment]
Сценарий - Создать ЗаписьТекста(ПутьФайла), Сделать только ЗаписатьСтроку, без использования Закрыть, далее открыть файл и проверить наличие добавленной строки.

**Comment by EvilBeaver** [comment]
@artbear хз, У Меня Все Работает (тм)
Я понимаю, конечно, всю нелепость этой фразы ) Но как мне воспроизвести?

**Comment by artbear** [comment]
Я проверял на 11 версии или ранее.
Проверю на 12, отпишусь.

**Comment by EvilBeaver** [comment]
@artbear есть новости по этой задаче? Как исследования?

**Comment by artbear** [comment]
Руки не дошли, возможно,на выходных смогу посмотреть

чт, 7 Апр 2016, 12:06 Andrei Ovsiankin notifications@github.com:

**Comment by artbear** [comment]
@EvilBeaver Проверил поведение. Все верно, проблему считаю закрытой.
Залил тест "Проверка немедленной записи в файл без буферизации при использовании ЗаписьТекста.ЗаписатьСтроку" для репозитария 1script
