### ISSUE TITLE
"ЛокальныйКаталогГит" или "Адрес удаленного репозитория GIT."

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/oscript-library#78]
Эта строчка сделала мой день :smile: 
https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/src/gitsync.os#L64

**Comment by EvilBeaver** [comment]
Это ж вроде я исправил, не?

**Comment by dmpas** [comment]
@EvilBeaver видимо, в тысяче мест исправил, а тут пропустил :smile:

**Comment by EvilBeaver** [comment]
Спасибо за задачку. Без формального закрепления это часто вылетает из поля зрения!
