### ISSUE TITLE
gitsync: при иерархической выгрузке не распаковывает толстые формы

### ISSUE THREAD

**Issue by dmpas** [EvilBeaver/oscript-library#79]
Добавить, чтобы распаковка срабатывала не только на `*.form`, но и на `Form.bin`

**Comment by artbear** [comment]
Что за файл form.bin?
Не помню файлы такого вида

ср, 30 Мар 2016, 9:54 Sergey Batanov notifications@github.com:

**Comment by dmpas** [comment]
@artbear Обычная форма при иерархической выгрузке выгружается в файл `Form.bin`. Например,
`Documents/Документ1/Forms/ФормаДокумента/Ext/Form.bin`.

**Comment by EvilBeaver** [comment]
Тут есть резонное возражение https://github.com/EvilBeaver/oscript-library/issues/88#issuecomment-214627153

**Comment by dmpas** [comment]
@EvilBeaver там же есть резонный ответ на резонное возражение

**Comment by nixel2007** [comment]
@EvilBeaver Насколько я понимаю, @dmpas хочет помимо оригинального Form.bin рядом иметь распакованный вариант. Это не совсем то, что обсуждается в соседней теме (переименование исходника). :)

**Comment by pumbaEO** [comment]
А какая разница если мы распакуем bin рядышком и переименуем module --> module.bsl ? 
Если исходить только из принципа - смотрим и не меняем, то ничто не мешает. 
Если предоложить, что надо что-то поменять, то т.к. так необходима подготовка исходников для загрузки.

**Comment by nixel2007** [comment]
@pumbaEO 
распаковка "рядышком" не меняет сам файл исходника, переименование - меняет.

**Comment by pumbaEO** [comment]
тю, так можно и патчик сделать, @dmpas примешь path в v8unpack, что если module.bsl то при сборке превращать его в module? Т.е. так же как и сама 1с это делает, внутри то у нее не храниться расширение bsl...

**Comment by nixel2007** [comment]
@pumbaEO а в конфигураторе как загружать?

**Comment by pumbaEO** [comment]
Если распаковать form.bin то в конфигураторе в любом случаи загружаться будет form.bin , а если поменяли module то необходим собрать новый form.bin. В слуачии сборки нового form.bin можно играться с переименованиями, т.к. это вручную вряд-ли кто-то будет делать.

**Comment by EvilBeaver** [comment]
@artbear @dmpas закрыто-переоткрыто. Напомните, что делать с issue?

**Comment by artbear** [comment]
Я не увидел  результата в этой issue
Нет договоренностей и прочее.
@dmpas что скажешь?

**Comment by dmpas** [comment]
скажу, что получил, что хотел - обычные формы распаковываются рядом с бинарником. в моём случае нужно было только это.
