### ISSUE TITLE
В gitsync не работает синхронизация одного репозитария

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#8]
В gitsync не работает синхронизация одного репозитария :(
Причина: временная база, используемая для выгрузки модулей, создается пустая, т.к. вообще нет кода для создания этой базы с помощью полученного из хранилища файла конфигурации.

И далее вторая причина: не разбираются формы, т.к. в репозитарий не положили файлы для Unpackv8.exe

@EvilBeaver у меня буря эмоций по этой ошибке :(

**Comment by artbear** [comment]
Также заработала синхронизация по нескольким репозитариям

**Comment by EvilBeaver** [comment]
`у меня буря эмоций по этой ошибке :(`

@artbear, зачем эмоции, взял и исправил - опенсорс же ;)
