### ISSUE TITLE
gitsync: в Windows не верно формируется строка команды git

### ISSUE THREAD

**Issue by L0z4** [EvilBeaver/oscript-library#80]
при работе в windows падает выполнение команд git (pull / push, думаю, и другие аналогично)

[как пример](https://github.com/EvilBeaver/oscript-library/blob/3484bbc354336a3a883ab00de616f401e092a547/src/gitsync/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A1%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.os#L495)

явно не хватает экранирования для ИмяФайлаЛогаКоммита

Аналогично с экранированием в   [tool1cd](https://github.com/EvilBeaver/oscript-library/blob/3484bbc354336a3a883ab00de616f401e092a547/src/tool1cd/table-reader.os#L34)

**Comment by EvilBeaver** [comment]
@L0z4 правильно ли я понял, что речь идет о необходимости обрамления этих путей кавычками?

**Comment by L0z4** [comment]
@EvilBeaver да. расставляем заплатки в виде 
`+ """" + ПрефиксПути + РабочийКаталог() + """" +`

**Comment by EvilBeaver** [comment]
Исправлено. Спасибо @Gisborn!
