### ISSUE TITLE
Добавить метод ВыгрузитьИнформационнуюБазу() в библиотеку v8runner

### ISSUE THREAD

**Issue by AlexandrSHad** [EvilBeaver/oscript-library#85]
Могу попробовать сделать через pull request

**Comment by EvilBeaver** [comment]
Делайте, конечно :smile:

**Comment by pumbaEO** [comment]
Тогда и загрузить тоже, если нет :)
12 апр. 2016 г. 15:21 пользователь "Andrei Ovsiankin" <
notifications@github.com> написал:

**Comment by AlexandrSHad** [comment]
@pumbaEO загрузить то как раз есть.

**Comment by EvilBeaver** [comment]
@AlexandrSHad спасибо!
