### ISSUE TITLE
gitsync: Не раскладывает иерархически, если явно указан параметр "-format hierarchical" и платформа < 8.3.7

### ISSUE THREAD

**Issue by JohnyDeath** [EvilBeaver/oscript-library#89]
Дано: Платформа < 8.3.7
Ожидаю, что при указании параметра `-format hierarchical` выгрузка будет происходить с разбросом по папкам как и без указания этого параметра.
В данный момент все выгружается в одну папку и далее не происходит процедур иерархического распределения.

**Comment by EvilBeaver** [comment]
Постой, а на платформе меньше чем 8.3.7 и нет никакой иерархической выгрузки.
Как именно ты видишь исправление данной задачи? Проверять версию платформы и выдавать предупреждение?

**Comment by JohnyDeath** [comment]
Нет, предупреждение можно и не выдавать, а выгружать как раньше: в plain с ручной раскидкой по папкам

**Comment by EvilBeaver** [comment]
Иными словами:
- До версии 8.3.7 мы не знаем про этот флаг и работаем, как раньше работал v83unpack, полностью игнорируя ключ Формат
- После версии 8.3.7 мы знаем, что есть альтернативный режим и если указано plain, то ведем себя, как раньше, т.е. в стиле v83unpack.
- Если указано hierarchical, то полностью полагаемся на платформу и никакой доп. раскладки не делаем.

Верно?

**Comment by JohnyDeath** [comment]
Так точно

**Comment by nixel2007** [comment]
> После версии 8.3.7 мы знаем, что есть альтернативный режим и если указано plain, то ведем себя, как раньше, т.е. в стиле v83unpack.

эээ... выгружай-ка мне в иерархическом формате, но плоско?

**Comment by JohnyDeath** [comment]
По папочкам-то раскидать - обязательно. Иначе это просто месиво.
Ты предлагаешь не раскидывать вообще, при указании plain???

**Comment by EvilBeaver** [comment]
@nixel2007 до версии 8.3.7 не был никаких "плоско". Этот режим выгрузки просто назван неудачно. plain=legacy-hierarchical, hierarchical=native

**Comment by EvilBeaver** [comment]
Я еще предупреждение бы добавил, если человек задал ключ, но использует платформу, которая про этот ключ не знает, то нужно ему подсказать, что он получит не то, что хотел.

**Comment by JohnyDeath** [comment]
Если только просто в качестве дополнительной информации в поток, но не прерывая и не ломая основную работу

**Comment by JohnyDeath** [comment]
https://github.com/EvilBeaver/oscript-library/commit/f73a4d40f6141b46300ce889560c4db89bdf15a4
