### ISSUE TITLE
Json парсер  - Маскирование служебных символов. 

### ISSUE THREAD

**Issue by SergeFocus** [EvilBeaver/oscript-library#91]
@EvilBeaver При чтении файловых путей из .JSON файлаов под windows:
оказалось, что парсер преобразует весь текст с учетом
[следующего](https://github.com/EvilBeaver/oscript-library/blame/develop/src/json/src/json.os#L680)  в результате путь под Windos считывается не так как записан в .json . Например скрипт для тестирования [run-check.os](https://drive.google.com/open?id=0B8H0glvIpRfJVF9VWWlsUHJicm8) и [Main.json](https://drive.google.com/open?id=0B8H0glvIpRfJWTBqcU5FZy1DS2M) поместил в папку **.\temp** и выполнил команду **_oscript .\temp\run-check.os .\temp\Main.json_** из папки вышестоящей по отношению к \temp 
Преобразование путей из Main.json к*\* .\temp **происходит в виде** . emp **
Сам .json в кодировке UTF8.

**Comment by artbear** [comment]
Main.json

``` json
{
   "ВариантыСборок":[
   ".\temp\VBParams82OF.json",
   ".\temp\VBParams82UF.json",
   ".\temp\VBParams836OF.json",
   ".\temp\VBParams836UF.json",
   ".\temp\VBParams837UF.json",
   ".\temp\VBParams836UFnoSync.json"
   ]
}
```

run-check.os

``` VBScript
#Использовать logos
#Использовать json

Перем Лог;


Функция ПрочитатьФайлВСтроку(ИмяФайла)
    ФайлПроверкаСуществования = Новый Файл(ИмяФайла);
    Если НЕ ФайлПроверкаСуществования.Существует() Тогда
        ВызватьИсключение("Файл " + ИмяФайла + " не существует!");
    КонецЕсли;  


    Текст = Новый ЧтениеТекста;
    Текст.Открыть(ИмяФайла,"UTF-8");
    Рез = "";

    Пока Истина Цикл
        Стр = Текст.ПрочитатьСтроку();
        Если Стр = Неопределено Тогда
            Прервать;
        КонецЕсли;  

        Рез = Рез + Стр + Символы.ПС;
    КонецЦикла;   

    Текст.Закрыть();

    Возврат  Рез;
КонецФункции    

Функция ПрочитатьФайлJSON(ИмяФайла)
    JsonСтрока  = ПрочитатьФайлВСтроку(ИмяФайла);
    ПарсерJSON  = Новый ПарсерJSON();
    Рез         = ПарсерJSON.ПрочитатьJSON(JsonСтрока);
    Сообщить("JSON файл" + JsonСтрока);
    Рез.Вставить("ИмяФайлаСборки",ИмяФайла);
    Возврат Рез;
КонецФункции




Процедура ВыполнитьЗапускВсехСборок(ОсновнойФайлПараметров)
    ОсновныеПараметры = ПрочитатьФайлJSON(ОсновнойФайлПараметров);
    КаталогиДляОчистки = ОсновныеПараметры["КаталогиДляОчистки"];
    МассивВариантыСборок = ОсновныеПараметры["ВариантыСборок"];
    Сборки = Новый Массив;
    Для каждого ИмяФайлаВариантСборки Из МассивВариантыСборок Цикл
        ФайлПроверкаСуществования = Новый Файл(ИмяФайлаВариантСборки);
        Сообщить("ИмяФайлаВариантСборки " +  ИмяФайлаВариантСборки);
    КонецЦикла;   

КонецПроцедуры


Если АргументыКоманднойСтроки.Количество() = 0 Тогда
    Лог.Ошибка("Не передан файл параметров!");
    //Возврат;
ИначеЕсли АргументыКоманднойСтроки.Количество() > 1 Тогда
    Лог.Ошибка("Скрипт принимает только один параметр!");
    //Возврат;
Иначе  
    ВыполнитьЗапускВсехСборок(АргументыКоманднойСтроки[0]);
КонецЕсли;
```

**Comment by artbear** [comment]
Выполнил команду `oscript .\temp\run-check.os .\temp\Main.json` 
Получил результат

```
JSON файл{                                                                            
   "ВариантыСборок":[                                                                 
   ".\temp\VBParams82OF.json",                                                        
   ".\temp\VBParams82UF.json",                                                        
   ".\temp\VBParams836OF.json",                                                       
   ".\temp\VBParams836UF.json",                                                       
   ".\temp\VBParams837UF.json",                                                       
   ".\temp\VBParams836UFnoSync.json"                                                  
   ]                                                                                  
}                                                                                     

ИмяФайлаВариантСборки . emp\VBParams82OF.json                                         
ИмяФайлаВариантСборки . emp\VBParams82UF.json                                         
ИмяФайлаВариантСборки . emp\VBParams836OF.json                                        
ИмяФайлаВариантСборки . emp\VBParams836UF.json                                        
ИмяФайлаВариантСборки . emp\VBParams837UF.json                                        
ИмяФайлаВариантСборки . emp\VBParams836UFnoSync.json
```

что неверно

**Comment by artbear** [comment]
@SergeFocus не вижу проблему в [указанном Вами коде](https://github.com/EvilBeaver/oscript-library/blame/develop/src/json/src/json.os#L680)
Лишних/неверных замен ИМХО не проводится

**Comment by nixel2007** [comment]
>  Лишних/неверных замен ИМХО не проводится

@artbear Артур, ну ты чего. та функция принудительно парсит строку, как регулярку, даже если это обычная строка. Если я передаю в функцию строку с путем вида "\build", я ожидаю, что на выходе я получу "\build", а не обрезок без "\b", так как это boundary-разделитель для регулярки.

**Comment by artbear** [comment]
@nixel2007 Упс, недоглядел :)

**Comment by nixel2007** [comment]
@SergeFocus как быстрый хот-фикс могу предложить прописывать такие пути как `.\\temp`:

```
JSON файл{
   "ВариантыСборок":[
   ".\\temp\VBParams82OF.json",
   ".\\temp\VBParams82UF.json",
   ".\\temp\VBParams836OF.json",
   ".\\temp\VBParams836UF.json",
   ".\\temp\VBParams837UF.json",
   ".\\temp\VBParams836UFnoSync.json"
   ]
}

ИмяФайлаВариантСборки .\temp\VBParams82OF.json
ИмяФайлаВариантСборки .\temp\VBParams82UF.json
ИмяФайлаВариантСборки .\temp\VBParams836OF.json
ИмяФайлаВариантСборки .\temp\VBParams836UF.json
ИмяФайлаВариантСборки .\temp\VBParams837UF.json
ИмяФайлаВариантСборки .\temp\VBParams836UFnoSync.json
```

**Comment by nixel2007** [comment]
А для решения этой проблемы предлагаю добавить в функцию новый параметр, который будет определять необходимость замены таких служебных символов.

Если хотим оставить обратную совместимость, то по умолчанию он будет `Истина`

**Comment by artbear** [comment]
Получается, что у нас читатель JSON вообще неработоспособный ?

**Comment by nixel2007** [comment]
@artbear спорно. надо посмотреть, как ведут себя такого рода парсеры в соседних языках.

upd: для начала - родной парсер 1С

**Comment by pumbaEO** [comment]
/ используйте
05 мая 2016 г. 18:19 пользователь "Nikita Gryzlov" notifications@github.com
написал:

**Comment by artbear** [comment]
В наших и соседних проектах, оказывается, сейчас есть 2 парсера JSON
- наш из сабжа
- вариант на чистом 1С с Инфостарта, например, используется в vanessa-behavior

В последнем варианте нет таких проблем, т.к. там вообще нет маскирования

Подобный дубль это не очень хорошо :(

**Comment by SergeFocus** [comment]
Для Windows просто в .Json после \ писал большую букву - для путей отрабатывает нормально

**Comment by nixel2007** [comment]
@artbear 

> В последнем варианте нет таких проблем, т.к. там вообще нет маскирования

а платформенный метод?

**Comment by artbear** [comment]
Платформенный метод - это 3 вариант.
Я его пока не проверял.

**Comment by artbear** [comment]
Обновил свое мнение.
Текущее поведение парсера JSON все-таки правильное и соответствует формату JSON
Но данное поведение не очень дружелюбно к вводу данных человеком.

Для упрощения предлагаю воспользоваться предложением @nixel2007 и сделать доп.параметр для управления поведением демаскирования.

**Comment by SergeFocus** [comment]
> Платформенный метод - это 3 вариант.

Начиная с версии 8.3.6.1977 есть метод ЧтениеJSON
Так вот встречая в строке символ **.\**  он отваливается с ошибкой:
**_непредвиденный символ при чтении json _**
конструкция c двумя подряд **.\** проходит как положено.
@pumbaEO  прав. нужно  просто использовать ее и не отходить от стандарта.
Хотя быстрее и более читаемо  **.\**
Так что получается не БАГ а ФИЧА :)

**Comment by EvilBeaver** [comment]
Закрываю. Текущий пакет является почти 100% копипастой с модуля json на инфостарте. Об этом, кстати, написано в README. Абстрактное "удобство" не повод менять стандарты json.
