### ISSUE TITLE
gitsync: Исправить имя бинарного файла "unpackV8.exe" на штатное "v8unpack.exe"

### ISSUE THREAD

**Issue by artbear** [EvilBeaver/oscript-library#99]

**Comment by EvilBeaver** [comment]
@artbear поясни, плиз

**Comment by ghost** [comment]
@EvilBeaver 

![](https://files.gitter.im/silverbulleters/vanessa-behavior/sQYh/thumb/2016-05-19_18-39-13.png)

![](https://files.gitter.im/silverbulleters/vanessa-behavior/xFQC/thumb/2016-05-19_18-41-28.png)

https://gitter.im/silverbulleters/vanessa-behavior - отсюда задача

**Comment by artbear** [comment]
Все-таки у продукта `v8unpack` имя исполняемого файла `v8unpack.exe`
А у нас до сих пор почему-то другое имя :(
Вот и предлагаю исправить имя бинарного файла "unpackV8.exe" на штатное "v8unpack.exe"

**Comment by JohnyDeath** [comment]
Всё это тянется с v83unpack. Тогда @pumbaEO положил бинарник с именем unpackV8 в свой репо. По-моему мы с ним даже обсуждали этот вопрос. Но далее пошел порт на oscript, который был по сути калькой v83unpack. Именно поэтому такое имя и висит сейчас в репо 1script.

**Comment by JohnyDeath** [comment]
В общем, просто один раз положили с неверным именем, теперь оно так и тянется в нескольких других проектах

**Comment by pumbaEO** [comment]
кровавый энтерпрайз

**Comment by JohnyDeath** [comment]
Артур, так просто взять и переименовать не получится.
Как минимум вот: https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9C%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%A1%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.os#L1076

**Comment by artbear** [comment]
@JohnyDeath не увидел обновлений :) обновился, исправил.
